In [1]:
### Tim Johansson
### Back Tester 
### 2021-01-28

### Goal to make a program that can backtest strategies.
#1. The program will have function that let the user define the entry of the strategy
#2. The program will have function that let the user define the stop loss of the strategy
#3. The program will have function that let hte user define the exit / profit of the strategy
#4. The program will have a function that let the user define the bias of the strategy

#5. The program will have function that will track data about the strategy, net account balance after trade, amount of winning trades
#5.1. Net account balance after the test
#5.2. Amount of winning / losing trade
#5.3. Ratio avarge winning / losing
#5.4. Max consecutive wins / losses
#5.5. Largest winning / losing
#5.6. Max amount of contract traded
#5.7. Etc


"""
1. I will need a dataframe to hold all information about the trade.
2. I will need a dataframe to hold data about indicator, cot data, IG sentiment, moving average, etc. 
3. I will need a function to hold data about everything and then execute on the information it gets. 

"""

"""
Hi!
This project is not completley yet. I'm just showcasing what I have done so far and how I code. 



"""

In [2]:
# Importing the library that will be used
import pandas as pd
import MetaTrader5 as mt5
from datetime import datetime
from datetime import timedelta

In [3]:
### PRICE DATA EURUSD###

# Getting price data and formatting it
price_data = pd.read_csv(r'C:\Users\timmo\Google Drive\1.Trading\4.Data\price_df.csv')

# Setting time to datetime library
price_data["time"] = pd.to_datetime(price_data["time"])

# Adding day to date
price_data["day"] = price_data["time"].dt.day_name()

# Setting the date as index
price_data.set_index("time" , inplace = True)

In [4]:
### COT DATA ### 


## Improve by downloading the data directly from COT website and then appending the value for every week to dataframe.
## Improve by appending data automatic to same dataframe and remove duplication.
## Improve by making a function and then be able to append data for each currency pair.


# Getting that COT data and formatting it
cot_data = pd.read_excel(r'C:\Users\timmo\Google Drive\1.Trading\4.Data\COT\dea_fut_xls_1986_2016\FUT86_06.xls' , parse_dates = ["Report_Date_as_MM_DD_YYYY"])

# Setting the date as index
cot_data.set_index("Report_Date_as_MM_DD_YYYY" , inplace = True)

# Filter EURUSD and GBPUSD and setting variable for the data
cot_data_EURUSD = cot_data[cot_data["Market_and_Exchange_Names"].isin(["EURO FX - CHICAGO MERCANTILE EXCHANGE"])]
cot_data_GBPUSD = cot_data[cot_data["Market_and_Exchange_Names"].isin(["BRITISH POUND STERLING - CHICAGO MERCANTILE EXCHANGE"])] 

# Filling out the week with days and then fill the days with values for that week
cot_data_EURUSD = cot_data_EURUSD.resample("D").ffill()
cot_data_GBPUSD = cot_data_GBPUSD.resample("D").ffill()


# Appending the data to CSV file on my google drive
cot_data_EURUSD.to_csv(r"C:\Users\timmo\Google Drive\1.Trading\4.Data\COT\cot_data_EURUSD.csv" , mode = "a" , index = True)
cot_data_GBPUSD.to_csv(r"C:\Users\timmo\Google Drive\1.Trading\4.Data\COT\cot_data_GBPUSD.csv" , mode = "a" , index = True)

WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero

In [211]:
cot_data_index

,Market_and_Exchange_Names,As_of_Date_In_Form_YYMMDD,CFTC_Contract_Market_Code,CFTC_Market_Code,CFTC_Region_Code,CFTC_Commodity_Code,Open_Interest_All,NonComm_Positions_Long_All,NonComm_Positions_Short_All,NonComm_Postions_Spread_All,Comm_Positions_Long_All,Comm_Positions_Short_All,Tot_Rept_Positions_Long_All,Tot_Rept_Positions_Short_All,NonRept_Positions_Long_All,NonRept_Positions_Short_All,Open_Interest_Old,NonComm_Positions_Long_Old,NonComm_Positions_Short_Old,NonComm_Positions_Spread_Old,Comm_Positions_Long_Old,Comm_Positions_Short_Old,Tot_Rept_Positions_Long_Old,Tot_Rept_Positions_Short_Old,NonRept_Positions_Long_Old,NonRept_Positions_Short_Old,Open_Interest_Other,NonComm_Positions_Long_Other,NonComm_Positions_Short_Other,NonComm_Positions_Spread_Other,Comm_Positions_Long_Other,Comm_Positions_Short_Other,Tot_Rept_Positions_Long_Other,Tot_Rept_Positions_Short_Other,NonRept_Positions_Long_Other,NonRept_Positions_Short_Other,Change_in_Open_Interest_All,Change_in_NonComm_Long_All,Change_in_NonComm_Short_All,Change_in_NonComm_Spead_All,Change_in_Comm_Long_All,Change_in_Comm_Short_All,Change_in_Tot_Rept_Long_All,Change_in_Tot_Rept_Short_All,Change_in_NonRept_Long_All,Change_in_NonRept_Short_All,Pct_of_Open_Interest_All,Pct_of_OI_NonComm_Long_All,Pct_of_OI_NonComm_Short_All,Pct_of_OI_NonComm_Spread_All,Pct_of_OI_Comm_Long_All,Pct_of_OI_Comm_Short_All,Pct_of_OI_Tot_Rept_Long_All,Pct_of_OI_Tot_Rept_Short_All,Pct_of_OI_NonRept_Long_All,Pct_of_OI_NonRept_Short_All,Pct_of_Open_Interest_Old,Pct_of_OI_NonComm_Long_Old,Pct_of_OI_NonComm_Short_Old,Pct_of_OI_NonComm_Spread_Old,Pct_of_OI_Comm_Long_Old,Pct_of_OI_Comm_Short_Old,Pct_of_OI_Tot_Rept_Long_Old,Pct_of_OI_Tot_Rept_Short_Old,Pct_of_OI_NonRept_Long_Old,Pct_of_OI_NonRept_Short_Old,Pct_of_Open_Interest_Other,Pct_of_OI_NonComm_Long_Other,Pct_of_OI_NonComm_Short_Other,Pct_of_OI_NonComm_Spread_Other,Pct_of_OI_Comm_Long_Other,Pct_of_OI_Comm_Short_Other,Pct_of_OI_Tot_Rept_Long_Other,Pct_of_OI_Tot_Rept_Short_Other,Pct_of_OI_NonRept_Long_Other,Pct_of_OI_NonRept_Short_Other,Traders_Tot_All,Traders_NonComm_Long_All,Traders_NonComm_Short_All,Traders_NonComm_Spread_All,Traders_Comm_Long_All,Traders_Comm_Short_All,Traders_Tot_Rept_Long_All,Traders_Tot_Rept_Short_All,Traders_Tot_Old,Traders_NonComm_Long_Old,Traders_NonComm_Short_Old,Traders_NonComm_Spead_Old,Traders_Comm_Long_Old,Traders_Comm_Short_Old,Traders_Tot_Rept_Long_Old,Traders_Tot_Rept_Short_Old,Traders_Tot_Other,Traders_NonComm_Long_Other,Traders_NonComm_Short_Other,Traders_NonComm_Spread_Other,Traders_Comm_Long_Other,Traders_Comm_Short_Other,Traders_Tot_Rept_Long_Other,Traders_Tot_Rept_Short_Other,Conc_Gross_LE_4_TDR_Long_All,Conc_Gross_LE_4_TDR_Short_All,Conc_Gross_LE_8_TDR_Long_All,Conc_Gross_LE_8_TDR_Short_All,Conc_Net_LE_4_TDR_Long_All,Conc_Net_LE_4_TDR_Short_All,Conc_Net_LE_8_TDR_Long_All,Conc_Net_LE_8_TDR_Short_All,Conc_Gross_LE_4_TDR_Long_Old,Conc_Gross_LE_4_TDR_Short_Old,Conc_Gross_LE_8_TDR_Long_Old,Conc_Gross_LE_8_TDR_Short_Old,Conc_Net_LE_4_TDR_Long_Old,Conc_Net_LE_4_TDR_Short_Old,Conc_Net_LE_8_TDR_Long_Old,Conc_Net_LE_8_TDR_Short_Old,Conc_Gross_LE_4_TDR_Long_Other,Conc_Gross_LE_4_TDR_Short_Other,Conc_Gross_LE_8_TDR_Long_Other,Conc_Gross_LE_8_TDR_Short_Other,Conc_Net_LE_4_TDR_Long_Other,Conc_Net_LE_4_TDR_Short_Other,Conc_Net_LE_8_TDR_Long_Other,Conc_Net_LE_8_TDR_Short_Other,Contract_Units
Report_Date_as_MM_DD_YYYY,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2000-08-29,EURO FX - CHICAGO MERCANTILE EXCHANGE,829,99741,CME,0,99,73012,13536,12330,39,25725,40097,39300,52466,33712,20546,73012,13536,12330,39,25725,40097,39300,52466,33712,20546,0,0,0,0,0,0,0,0,0,0,2339.0,957.0,3111.0,1.0,17.0,-2742.0,975.0,370.0,1364.0,1969.0,100,18.5,16.9,0.1,35.2,54.9,53.8,71.9,46.2,28.1,100,18.5,16.9,0.1,35.2,54.9,53.8,71.9,46.2,28.1,100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,59,15,11,3,22,21,37,35,59,15,11,3,22,21,37,35,0,0,0,0,0,0,0,0,24.6,31.3,33.5,46.5,24.6,30.6,33.2,45.7,24.6,31.3,33.5,46.5,24.6,30.6,33.2,45.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"(CONTRACTS OF 125,000 EUROS)"
2000-08-30,EURO FX - CHICAGO MERCANTILE EXCHANGE,829,99741,CME,0,99,73012,13536,12330,39,25725,40097,39300,52466,33712,20546,73012,13536,12330,39,25725,40097,39300,52466,33712,20546,0,0,0,0,0,0,0,0,0,0,2339.0,957.0,3111.0,1.0,17.0,-2742.0,975.0,370.0,1364.0,1969.0,100,18.5,16.9,0.1,35.2,54.9,53.8,71.9,46.2,28.1,100,18.5,16.9,0.1,35.2,54.9,53.8,71.9,46.2,28.1,100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,59,15,11,3,22,21,37,35,59,15,11,3,22,21,37,35,0,0,0,0,0,0,0,0,24.6,31.3,33.5,46.5,24.6,30.6,33.2,45.7,24.6,31.3,33.5,46.5,24.6,30.6,33.2,45.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"(CONTRACTS OF 125,000 EUROS)"
2000-08-31,EURO FX - CHICAGO MERCANTILE EXCHANGE,829,99741,CME,0,99,73012,13536,12330,39,25725,40097,39300,52466,33712,20546,73012,13536,12330,39,25725,40097,39300,52466,33712,20546,0,0,0,0,0,0,0,0,0,0,2339.0,957.0,3111.0,1.0,17.0,-2742.0,975.0,370.0,1364.0,1969.0,100,18.5,16.9,0.1,35.2,54.9,53.8,71.9,46.2,28.1,100,18.5,16.9,0.1,35.2,54.9,53.8,71.9,46.2,28.1,100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,59,15,11,3,22,21,37,35,59,15,11,3,22,21,37,35,0,0,0,0,0,0,0,0,24.6,31.3,33.5,46.5,24.6,30.6,33.2,45.7,24.6,31.3,33.5,46.5,24.6,30.6,33.2,45.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"(CONTRACTS OF 125,000 EUROS)"
2000-09-01,EURO FX - CHICAGO MERCANTILE EXCHANGE,829,99741,CME,0,99,73012,13536,12330,39,25725,40097,39300,52466,33712,20546,73012,13536,12330,39,25725,40097,39300,52466,33712,20546,0,0,0,0,0,0,0,0,0,0,2339.0,957.0,3111.0,1.0,17.0,-2742.0,975.0,370.0,1364.0,1969.0,100,18.5,16.9,0.1,35.2,54.9,53.8,71.9,46.2,28.1,100,18.5,16.9,0.1,35.2,54.9,53.8,71.9,46.2,28.1,100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,59,15,11,3,22,21,37,35,59,15,11,3,22,21,37,35,0,0,0,0,0,0,0,0,24.6,31.3,33.5,46.5,24.6,30.6,33.2,45.7,24.6,31.3,33.5,46.5,24.6,30.6,33.2,45.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"(CONTRACTS OF 125,000 EUROS)"
2000-09-02,EURO FX - CHICAGO MERCANTILE EXCHANGE,829,99741,CME,0,99,73012,13536,12330,39,25725,40097,39300,52466,33712,20546,73012,13536,12330,39,25725,40097,39300,52466,33712,20546,0,0,0,0,0,0,0,0,0,0,2339.0,957.0,3111.0,1.0,17.0,-2742.0,975.0,370.0,1364.0,1969.0,100,18.5,16.9,0.1,35.2,54.9,53.8,71.9,46.2,28.1,100,18.5,16.9,0.1,35.2,54.9,53.8,71.9,46.2,28.1,100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,59,15,11,3,22,21,37,35,59,15,11,3,22,21,37,35,0,0,0,0,0,0,0,0,24.6,31.3,33.5,46.5,24.6,30.6,33.2,45.7,24.6,31.3,33.5,46.5,24.6,30.6,33.2,45.7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"(CONTRACTS OF 125,000 EUROS)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2006-12-22,EURO FX - CHICAGO MERCANTILE EXCHANGE,61219,99741,CME,0,99,194079,110993,19023,1521,19007,144006,131521,164550,62558,29529,194079,110993,19023,1521,19007,144006,131521,164550,62558,29529,0,0,0,0,0,0,0,0,0,0,-36166.0,-1195.0,3518.0,-4368.0,-27466.0,-31711.0,-33029.0,-32561.0,-3137.0,-3605.0,100,57.2,9.8,0.8,9.8,74.2,67.8,84.8,32.2,15.2,100,57.2,9.8,0.8,9.8,74.2,67.8,84.8,32.2,15.2,100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,128,68,22,12,23,22,95,53,128,68,22,12,23,22,95,53,0,0,0,0,0,0,0,0,18.5,49.5,27.0,65.3,18.5,49.3,26.9,65.1,18.5,49.5,27.0,65.3,18.5,49.3,26.9,65.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"(CONTRACTS OF 125,000 EUROS)"
2006-12-23,EURO FX - CHICAGO MERCANTILE EXCHANGE,61219,99741,CME,0,99,194079,110993,19023,1521,19007,144006,131521,164550,62558,29529,194079,110993,19023,1521,19007,144006,131521,164550,62558,29529,0,0,0,0,0,0,0,0,0,0,-36166.0,-1195.0,3518.0,-4368.0,-27466.0,-31711.0,-33029.0,-32561.0,-3137.0,-3605.0,100,57.2,9.8,0.8,9.8,74.2,67.8,84.8,32.2,15.2,100,57.2,9.8,0.8,9.8,74.2,67.8,84.8,32.2,15.2,100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,128,68,22,12,23,22,95,53,128,68,22,12,23,22,95,53,0,0,0,0,0,0,0,0,18.5,49.5,27.0,65.3,18.5,49.3,26.9,65.1,18.5,49.5,27.0,65.3,18.5,49.3,26.9,65.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"(CONTRACTS OF 125,000 EUROS)"
2006-12-24,EURO FX - CHICAGO MERCANTILE EXCHANGE,61219,99741,CME,0,99,194079,110993,19023,1521,19007,144006,131521,164550,62558,29529,194079,110993,19023,1521,19007,144006,131521,164550,62558,29529,0,0,0,0,0,0,0,0,0,0,-36166.0,-1195.0,3518.0,-4368.0,-27466.0,-31711.0,-33029.0,-32561.0,-3137.0,-3605.0,100,57.2,9.8,0.8,9.8,74.2,67.8,84.8,32.2,15.2,100,57.2,9.8,0.8,9.8,74.2,67.8,84.8,32.2,15.2,100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,128,68,22,12,23,22,95,53,128,68,22,12,23,22,95,53,0,0,0,0,0,0,0,0,18.5,49.5,27.0,65.3,18.5,49.3,26.9,65.1,18.5,49.5,27.0,65.3,18.5,49.3,26.9,65.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"(CONTRACTS OF 125,000 EUROS)"
2006-12-25,EURO FX - CHICAGO MERCANTILE EXCHANGE,61219,99741,CME,0,99,194079,110993,19023,1521,19007,144006,131521,164550,62558,29529,194079,110993,19023,1521,19007,144006,131521,164550,62558,29529,0,0,0,0,0,0,0,0,0,0,-36166.0,-1195.0,3518.0,-4368.0,-27466.0,-31711.0,-33029.0,-32561.0,-3137.0,-3605.0,100,57.2,9.8,0.8,9.8,74.2,67.8,84.8,32.2,15.2,100,57.2,9.8,0.8,9.8,74.2,67.8,84.8,32.2,15.2,100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,128,68,22,12,23,22,95,53,128,68,22,12,23,22,95,53,0,0,0,0,0,0,0,0,18.5,49.5,27.0,65.3,18.5,49.3,26.9,65.1,18.5,49.5,27.0,65.3,18.5,49.3,26.9,65.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"(CONTRACTS OF 125,000 EUROS)"
2006-12-26,EURO FX - CHICAGO MERCANTILE EXCHANGE,61226,99741,CME,0,99,186755,100959,20989,1788,22399,138364,125146,161141,61609,25614,186755,100959,20989,1788,22399,138364,125146,161141,61609,25614,0,0,0,0,0,0,0,0,0,0,-7324.0,-10034.0,1966.0,267.0,3392.0,-5642.0,-6375.0,-3409.0,-949.0,-3915.0,100,54.1,11.2,1.0,12.0,74.1,67.0,86.3,33.0,13.7,100,54.1,11.2,1.0,12.0,74.1,67.0,86.3,33.0,13.7,100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,124,61,24,13,24,22,89,56,124,61,24,13,24,22,89,56,0,0,0,0,0,0,0,0,20.0,48.1,28.3,65.3,19.9,47.6,28.2,64.9,20.0,48.1,28.3,65.3,19.9,47.6,28.2,64.9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,"(CONTRACTS OF 125,000 EUROS)"

In [164]:
### COT NET POSITION ###

# List of all the parties
commercial_cot_net = []
noncommercial_cot_net = []
nonrept_cot_net = []

#List of the date
today_list = []

# Setting up a for loop to look through data and calculate net position for all parties
for today in cot_data_index.index:
    
    # Appending today to list
    today_list.append(today)
    
    # Commercials
    today_cot_long = cot_data_index.loc[today, ["Comm_Positions_Long_All"]]
    today_cot_short = cot_data_index.loc[today, ["Comm_Positions_Short_All"]]  
    commercial_cot_net.append(int(today_cot_long) - int(today_cot_short) )
    
    # Non - Commercials
    today_cot_long = cot_data_index.loc[today, ["NonComm_Positions_Long_All"]]
    today_cot_short = cot_data_index.loc[today, ["NonComm_Positions_Short_All"]]  
    noncommercial_cot_net.append(int(today_cot_long) - int(today_cot_short))
    
    # Non - Reportable
    today_cot_long = cot_data_index.loc[today, ["NonRept_Positions_Long_All"]]
    today_cot_short = cot_data_index.loc[today, ["NonRept_Positions_Short_All"]]  
    nonrept_cot_net.append(int(today_cot_long) - int(today_cot_short))

# Creating dictionary to hold all data
net_cot_data = {"date" : today_list,
                "commercials_net" : commercial_cot_net,
                "non_commercials_net" : noncommercial_cot_net,
                "non_rept_net" : nonrept_cot_net}

# Change date to index
net_cot_data = pd.DataFrame(data = net_cot_data, index = today_list)
net_cot_data = net_cot_data.set_index("date")

# Exporting dataframe 
net_cot_data.to_csv(r'C:\Users\timmo\Google Drive\1.Trading\4.Data\COT\net_cot_data_eurusd.csv',  mode = "a")

In [209]:
### COT INDEX ### 

# Getting the data
cot_data_net = pd.read_csv(r'C:\Users\timmo\Google Drive\1.Trading\4.Data\COT\net_cot_data_eurusd.csv' , parse_dates = ["date"])

# Setting dates as index
cot_data_net.set_index("date" , inplace = True)

# Setting time delta of data 3 years ago
tdelta = timedelta(days = -1095)

# Lists
today_list = []
cot_index_list = []

for today in cot_data_net.index:
    
    # Converting today string to datetime
    today_three_year_ago = today + tdelta
    
    # Commercial cot index
    
    print("\n")

    # Commercial net today 
    com_cot_net_today = cot_data_net.loc[today, ["commercials_net"]]
    print("Commercials today net: ")
    print(com_cot_net_today)
    
    
    # Commercial net 3 years ago max and min
        
    print("\n")
    
    # Check validity of old period
    try:
        cot_data_net.loc[today_three_year_ago, ["commercials_net"]]
    except KeyError:
        print("No value for this time périod. ")
        
    # If validity ok then check for max and min
    else:
        # Max
        com_cot_net_old_max = cot_data_net.loc[today_three_year_ago:today, ["commercials_net"]].max()
        print("Commercial max past 3 years")
        print(com_cot_net_old_max)
        
        # Min
        com_cot_net_old_min = cot_data_net.loc[today_three_year_ago:today, ["commercials_net"]].min()
        print("Commercial min past 3 years")
        print(com_cot_net_old_min)
        
        # Calculate cot index
        cot_index = ((int(com_cot_net_today) - int(com_cot_net_old_min))/(int(com_cot_net_old_max) - int(com_cot_net_old_min)))*100
       
        # Appending cot index and date into a list
        cot_index_list.append(cot_index)
        today_list.append(today)
        
        print("\n")
        print("COT INDEX: ")
        print(cot_index)

        
# Putting data into a dataframe and exporting it to csv
cot_index_data = {"date" : today_list, "cot_index" : cot_index_list}

cot_index_data = pd.DataFrame(data = cot_index_data, index = today_list)
cot_index_data = cot_index_data.set_index("date")

# Exporting data frame
cot_index_data.to_csv(r'C:\Users\timmo\Google Drive\1.Trading\4.Data\COT\cot_index_eurusud.csv', mode = "a")

Commercials today net:
commercials_net   -14372
Name: 2000-08-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -14372
Name: 2000-08-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -14372
Name: 2000-08-31 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -14372
Name: 2000-09-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -14372
Name: 2000-09-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -14372
Name: 2000-09-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -14372
Name: 2000-09-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16197
Name: 2000-09-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16197
Name: 2000-09-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16197
Name: 2000-09-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16197
Name: 2000-09-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16197
Name: 2000-09-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16197
Name: 2000-09-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16197
Name: 2000-09-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -20672
Name: 2000-09-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -20672
Name: 2000-09-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -20672
Name: 2000-09-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -20672
Name: 2000-09-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -20672
Name: 2000-09-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -20672
Name: 2000-09-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -20672
Name: 2000-09-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -13180
Name: 2000-09-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -13180
Name: 2000-09-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -13180
Name: 2000-09-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -13180
Name: 2000-09-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -13180
Name: 2000-09-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -13180
Name: 2000-09-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -13180
Name: 2000-09-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -15210
Name: 2000-09-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -15210
Name: 2000-09-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -15210
Name: 2000-09-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -15210
Name: 2000-09-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -15210
Name: 2000-09-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -15210
Name: 2000-10-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -15210
Name: 2000-10-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -19627
Name: 2000-10-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -19627
Name: 2000-10-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -19627
Name: 2000-10-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -19627
Name: 2000-10-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -19627
Name: 2000-10-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -19627
Name: 2000-10-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -19627
Name: 2000-10-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -23379
Name: 2000-10-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -23379
Name: 2000-10-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -23379
Name: 2000-10-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -23379
Name: 2000-10-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -23379
Name: 2000-10-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -23379
Name: 2000-10-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -23379
Name: 2000-10-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18146
Name: 2000-10-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18146
Name: 2000-10-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18146
Name: 2000-10-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18146
Name: 2000-10-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18146
Name: 2000-10-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18146
Name: 2000-10-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18146
Name: 2000-10-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18555
Name: 2000-10-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18555
Name: 2000-10-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18555
Name: 2000-10-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18555
Name: 2000-10-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18555
Name: 2000-10-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18555
Name: 2000-10-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18555
Name: 2000-10-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18812
Name: 2000-10-31 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18812
Name: 2000-11-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18812
Name: 2000-11-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18812
Name: 2000-11-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18812
Name: 2000-11-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18812
Name: 2000-11-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18812
Name: 2000-11-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -20350
Name: 2000-11-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -20350
Name: 2000-11-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -20350
Name: 2000-11-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -20350
Name: 2000-11-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -20350
Name: 2000-11-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -20350
Name: 2000-11-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -20350
Name: 2000-11-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -19859
Name: 2000-11-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -19859
Name: 2000-11-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -19859
Name: 2000-11-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -19859
Name: 2000-11-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -19859
Name: 2000-11-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -19859
Name: 2000-11-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -19859
Name: 2000-11-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -21601
Name: 2000-11-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -21601
Name: 2000-11-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -21601
Name: 2000-11-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -21601
Name: 2000-11-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -21601
Name: 2000-11-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -21601
Name: 2000-11-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -21601
Name: 2000-11-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -26881
Name: 2000-11-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -26881
Name: 2000-11-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -26881
Name: 2000-11-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -26881
Name: 2000-12-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -26881
Name: 2000-12-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -26881
Name: 2000-12-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -26881
Name: 2000-12-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39865
Name: 2000-12-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39865
Name: 2000-12-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39865
Name: 2000-12-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39865
Name: 2000-12-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39865
Name: 2000-12-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39865
Name: 2000-12-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39865
Name: 2000-12-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -46105
Name: 2000-12-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -46105
Name: 2000-12-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -46105
Name: 2000-12-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -46105
Name: 2000-12-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -46105
Name: 2000-12-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -46105
Name: 2000-12-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -46105
Name: 2000-12-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -52141
Name: 2000-12-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -52141
Name: 2000-12-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -52141
Name: 2000-12-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -52141
Name: 2000-12-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -52141
Name: 2000-12-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -52141
Name: 2000-12-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -52141
Name: 2000-12-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -55183
Name: 2000-12-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -55183
Name: 2000-12-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -55183
Name: 2000-12-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -55183
Name: 2000-12-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -55183
Name: 2000-12-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -55183
Name: 2000-12-31 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -55183
Name: 2001-01-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56085
Name: 2001-01-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56085
Name: 2001-01-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56085
Name: 2001-01-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56085
Name: 2001-01-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56085
Name: 2001-01-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56085
Name: 2001-01-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56085
Name: 2001-01-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -53271
Name: 2001-01-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -53271
Name: 2001-01-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -53271
Name: 2001-01-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -53271
Name: 2001-01-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -53271
Name: 2001-01-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -53271
Name: 2001-01-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -53271
Name: 2001-01-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -52251
Name: 2001-01-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -52251
Name: 2001-01-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -52251
Name: 2001-01-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -52251
Name: 2001-01-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -52251
Name: 2001-01-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -52251
Name: 2001-01-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -52251
Name: 2001-01-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -44493
Name: 2001-01-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -44493
Name: 2001-01-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -44493
Name: 2001-01-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -44493
Name: 2001-01-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -44493
Name: 2001-01-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -44493
Name: 2001-01-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -44493
Name: 2001-01-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45293
Name: 2001-01-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45293
Name: 2001-01-31 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45293
Name: 2001-02-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45293
Name: 2001-02-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45293
Name: 2001-02-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45293
Name: 2001-02-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45293
Name: 2001-02-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45438
Name: 2001-02-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45438

Commercials today net:
commercials_net   -24752
Name: 2001-03-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -20280
Name: 2001-03-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -20280
Name: 2001-03-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -20280
Name: 2001-03-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -20280
Name: 2001-03-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -20280
Name: 2001-03-31 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -20280
Name: 2001-04-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -20280
Name: 2001-04-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -23410
Name: 2001-04-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -23410
Name: 2001-04-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -23410
Name: 2001-04-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -23410
Name: 2001-04-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -23410
Name: 2001-04-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -23410
Name: 2001-04-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -23410
Name: 2001-04-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22309
Name: 2001-04-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22309
Name: 2001-04-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22309
Name: 2001-04-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22309
Name: 2001-04-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22309
Name: 2001-04-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22309
Name: 2001-04-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22309
Name: 2001-04-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -30240
Name: 2001-04-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -30240
Name: 2001-04-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -30240
Name: 2001-04-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -30240
Name: 2001-04-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -30240
Name: 2001-04-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -30240
Name: 2001-04-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -30240
Name: 2001-04-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -37617
Name: 2001-04-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -37617
Name: 2001-04-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -37617
Name: 2001-04-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -37617
Name: 2001-04-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -37617
Name: 2001-04-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -37617
Name: 2001-04-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -37617
Name: 2001-04-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -36434
Name: 2001-05-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -36434
Name: 2001-05-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -36434
Name: 2001-05-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -36434
Name: 2001-05-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -36434
Name: 2001-05-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -36434
Name: 2001-05-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -36434
Name: 2001-05-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31277
Name: 2001-05-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31277
Name: 2001-05-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31277
Name: 2001-05-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31277
Name: 2001-05-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31277
Name: 2001-05-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31277
Name: 2001-05-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31277
Name: 2001-05-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -25199
Name: 2001-05-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -25199
Name: 2001-05-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -25199
Name: 2001-05-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -25199
Name: 2001-05-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -25199
Name: 2001-05-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -25199
Name: 2001-05-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -25199
Name: 2001-05-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -14201
Name: 2001-05-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -14201
Name: 2001-05-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -14201
Name: 2001-05-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -14201
Name: 2001-05-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -14201
Name: 2001-05-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -14201
Name: 2001-05-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -14201
Name: 2001-05-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18037
Name: 2001-05-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18037
Name: 2001-05-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18037
Name: 2001-05-31 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18037
Name: 2001-06-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18037
Name: 2001-06-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18037
Name: 2001-06-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18037
Name: 2001-06-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -11942
Name: 2001-06-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -11942
Name: 2001-06-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -11942
Name: 2001-06-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -11942
Name: 2001-06-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -11942
Name: 2001-06-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -11942
Name: 2001-06-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -11942
Name: 2001-06-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -1569
Name: 2001-06-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -1569
Name: 2001-06-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -1569
Name: 2001-06-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -1569
Name: 2001-06-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -1569
Name: 2001-06-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -1569
Name: 2001-06-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -1569
Name: 2001-06-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -11964
Name: 2001-06-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -11964
Name: 2001-06-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -11964
Name: 2001-06-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -11964
Name: 2001-06-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -11964
Name: 2001-06-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -11964
Name: 2001-06-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -11964
Name: 2001-06-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -14670
Name: 2001-06-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -14670
Name: 2001-06-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -14670
Name: 2001-06-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -14670
Name: 2001-06-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -14670
Name: 2001-06-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -14670
Name: 2001-07-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -14670
Name: 2001-07-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -11647
Name: 2001-07-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -11647
Name: 2001-07-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -11647
Name: 2001-07-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -11647
Name: 2001-07-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -11647
Name: 2001-07-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -11647
Name: 2001-07-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -11647
Name: 2001-07-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16674
Name: 2001-07-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16674
Name: 2001-07-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16674
Name: 2001-07-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16674
Name: 2001-07-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16674
Name: 2001-07-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16674
Name: 2001-07-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16674
Name: 2001-07-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -24177
Name: 2001-07-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -24177
Name: 2001-07-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -24177
Name: 2001-07-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -24177
Name: 2001-07-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -24177
Name: 2001-07-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -24177
Name: 2001-07-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -24177
Name: 2001-07-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -37121
Name: 2001-07-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -37121
Name: 2001-07-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -37121
Name: 2001-07-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -37121
Name: 2001-07-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -37121
Name: 2001-07-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -37121
Name: 2001-07-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -37121
Name: 2001-07-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39383
Name: 2001-07-31 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39383
Name: 2001-08-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39383
Name: 2001-08-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39383
Name: 2001-08-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39383
Name: 2001-08-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39383
Name: 2001-08-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39383
Name: 2001-08-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -41506
Name: 2001-08-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -41506
Name: 2001-08-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -41506
Name: 2001-08-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -41506
Name: 2001-08-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -41506
Name: 2001-08-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -41506
Name: 2001-08-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -41506
Name: 2001-08-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -51637
Name: 2001-08-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -51637
Name: 2001-08-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -51637
Name: 2001-08-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -51637
Name: 2001-08-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -51637
Name: 2001-08-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -51637
Name: 2001-08-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -51637
Name: 2001-08-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57146
Name: 2001-08-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57146
Name: 2001-08-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57146
Name: 2001-08-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57146
Name: 2001-08-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57146
Name: 2001-08-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57146
Name: 2001-08-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57146
Name: 2001-08-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59876
Name: 2001-08-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59876
Name: 2001-08-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59876
Name: 2001-08-30 00:00:00, dtype: int64

No value for this time périod.


Commercials today net:
commercials_net   -59876
Name: 2001-08-31 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59876
Name: 2001-09-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59876
Name: 2001-09-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59876
Name: 2001-09-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -49078
Name: 2001-09-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -49078
Name: 2001-09-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -49078
Name: 2001-09-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -49078
Name: 2001-09-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -49078
Name: 2001-09-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -49078
Name: 2001-09-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43161
Name: 2001-09-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43161
Name: 2001-09-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43161
Name: 2001-09-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43161
Name: 2001-09-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43161
Name: 2001-09-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43161
Name: 2001-09-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43161
Name: 2001-09-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43161
Name: 2001-09-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58492
Name: 2001-09-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58492
Name: 2001-09-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58492
Name: 2001-09-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58492
Name: 2001-09-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58492
Name: 2001-09-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58492
Name: 2001-09-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58492
Name: 2001-09-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -62473
Name: 2001-09-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -62473
Name: 2001-09-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -62473
Name: 2001-09-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -62473
Name: 2001-09-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -62473
Name: 2001-09-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -62473
Name: 2001-09-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -62473
Name: 2001-10-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60905
Name: 2001-10-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60905
Name: 2001-10-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60905
Name: 2001-10-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60905
Name: 2001-10-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60905
Name: 2001-10-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60905
Name: 2001-10-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60905
Name: 2001-10-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60487
Name: 2001-10-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60487
Name: 2001-10-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60487
Name: 2001-10-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60487
Name: 2001-10-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60487
Name: 2001-10-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60487
Name: 2001-10-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60487
Name: 2001-10-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -49190
Name: 2001-10-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -49190
Name: 2001-10-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -49190
Name: 2001-10-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -49190
Name: 2001-10-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -49190
Name: 2001-10-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -49190
Name: 2001-10-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -49190
Name: 2001-10-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31312
Name: 2001-10-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31312
Name: 2001-10-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31312
Name: 2001-10-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31312
Name: 2001-10-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31312
Name: 2001-10-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31312
Name: 2001-10-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31312
Name: 2001-10-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -44794
Name: 2001-10-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -44794
Name: 2001-10-31 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -44794
Name: 2001-11-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -44794
Name: 2001-11-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -44794
Name: 2001-11-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -44794
Name: 2001-11-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -44794
Name: 2001-11-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -38579
Name: 2001-11-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -38579
Name: 2001-11-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -38579
Name: 2001-11-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -38579
Name: 2001-11-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -38579
Name: 2001-11-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -38579
Name: 2001-11-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -38579
Name: 2001-11-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22137
Name: 2001-11-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22137
Name: 2001-11-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22137
Name: 2001-11-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22137
Name: 2001-11-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22137
Name: 2001-11-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22137
Name: 2001-11-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22137
Name: 2001-11-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -13217
Name: 2001-11-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -13217
Name: 2001-11-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -13217
Name: 2001-11-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -13217
Name: 2001-11-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -13217
Name: 2001-11-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -13217
Name: 2001-11-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -13217
Name: 2001-11-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -10557
Name: 2001-11-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -10557
Name: 2001-11-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -10557
Name: 2001-11-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -10557
Name: 2001-11-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -10557
Name: 2001-12-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -10557
Name: 2001-12-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -10557
Name: 2001-12-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31130
Name: 2001-12-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31130
Name: 2001-12-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31130
Name: 2001-12-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31130
Name: 2001-12-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31130
Name: 2001-12-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31130
Name: 2001-12-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31130
Name: 2001-12-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -26442
Name: 2001-12-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -26442
Name: 2001-12-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -26442
Name: 2001-12-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -26442
Name: 2001-12-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -26442
Name: 2001-12-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -26442
Name: 2001-12-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -26442
Name: 2001-12-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -42216
Name: 2001-12-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -42216
Name: 2001-12-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -42216
Name: 2001-12-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -35948
Name: 2001-12-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -35948
Name: 2001-12-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -35948
Name: 2001-12-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -35948
Name: 2001-12-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -35948
Name: 2001-12-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -35948
Name: 2001-12-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -35948
Name: 2001-12-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -25890
Name: 2001-12-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -25890
Name: 2001-12-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -25890
Name: 2001-12-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -25890
Name: 2001-12-31 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -25890
Name: 2002-01-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -25890
Name: 2002-01-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -25890
Name: 2002-01-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -25890
Name: 2002-01-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -25890
Name: 2002-01-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -25890
Name: 2002-01-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -25890
Name: 2002-01-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43336
Name: 2002-01-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43336
Name: 2002-01-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43336
Name: 2002-01-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43336
Name: 2002-01-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43336
Name: 2002-01-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43336
Name: 2002-01-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43336
Name: 2002-01-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -35877
Name: 2002-01-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -35877
Name: 2002-01-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -35877
Name: 2002-01-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -35877
Name: 2002-01-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -35877
Name: 2002-01-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -35877
Name: 2002-01-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -35877
Name: 2002-01-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39524
Name: 2002-01-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39524
Name: 2002-01-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39524
Name: 2002-01-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39524
Name: 2002-01-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39524
Name: 2002-01-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39524
Name: 2002-01-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39524
Name: 2002-01-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16565
Name: 2002-01-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16565
Name: 2002-01-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16565
Name: 2002-01-31 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16565
Name: 2002-02-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16565
Name: 2002-02-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16565
Name: 2002-02-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16565
Name: 2002-02-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16718
Name: 2002-02-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16718
Name: 2002-02-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16718
Name: 2002-02-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -16718
Name: 2002-02-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:

No value for this time périod.


Commercials today net:
commercials_net   -21446
Name: 2002-02-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -21446
Name: 2002-02-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -21446
Name: 2002-02-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -21446
Name: 2002-02-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -21446
Name: 2002-02-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -26918
Name: 2002-02-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -26918
Name: 2002-02-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -26918
Name: 2002-02-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -26918
Name: 2002-02-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -26918
Name: 2002-02-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -26918
Name: 2002-02-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -26918
Name: 2002-02-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22389
Name: 2002-02-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22389
Name: 2002-02-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22389
Name: 2002-02-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22389
Name: 2002-03-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22389
Name: 2002-03-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22389
Name: 2002-03-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22389
Name: 2002-03-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -27210
Name: 2002-03-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -27210
Name: 2002-03-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -27210
Name: 2002-03-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -27210
Name: 2002-03-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -27210
Name: 2002-03-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -27210
Name: 2002-03-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -27210
Name: 2002-03-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -40471
Name: 2002-03-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -40471
Name: 2002-03-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -40471
Name: 2002-03-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -40471
Name: 2002-03-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -40471
Name: 2002-03-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -40471
Name: 2002-03-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -40471
Name: 2002-03-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -46264
Name: 2002-03-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -46264
Name: 2002-03-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -46264
Name: 2002-03-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -46264
Name: 2002-03-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -46264
Name: 2002-03-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -46264
Name: 2002-03-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -46264
Name: 2002-03-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -51243
Name: 2002-03-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -51243
Name: 2002-03-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -51243
Name: 2002-03-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -51243
Name: 2002-03-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -51243
Name: 2002-03-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -51243
Name: 2002-03-31 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -51243
Name: 2002-04-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -55304
Name: 2002-04-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -55304
Name: 2002-04-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -55304
Name: 2002-04-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -55304
Name: 2002-04-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -55304
Name: 2002-04-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -55304
Name: 2002-04-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -55304
Name: 2002-04-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -47752
Name: 2002-04-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -47752
Name: 2002-04-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -47752
Name: 2002-04-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -47752
Name: 2002-04-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -47752
Name: 2002-04-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -47752
Name: 2002-04-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -47752
Name: 2002-04-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56365
Name: 2002-04-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56365
Name: 2002-04-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56365
Name: 2002-04-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56365
Name: 2002-04-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56365
Name: 2002-04-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56365
Name: 2002-04-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56365
Name: 2002-04-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -63050
Name: 2002-04-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -63050
Name: 2002-04-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -63050
Name: 2002-04-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -63050
Name: 2002-04-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -63050
Name: 2002-04-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -63050
Name: 2002-04-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -63050
Name: 2002-04-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -69624
Name: 2002-04-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -69624
Name: 2002-05-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -69624
Name: 2002-05-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -69624
Name: 2002-05-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -69624
Name: 2002-05-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -69624
Name: 2002-05-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -69624
Name: 2002-05-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -75077
Name: 2002-05-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -75077
Name: 2002-05-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -75077
Name: 2002-05-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -75077
Name: 2002-05-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -75077
Name: 2002-05-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -75077
Name: 2002-05-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -75077
Name: 2002-05-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -72901
Name: 2002-05-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -72901
Name: 2002-05-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -72901
Name: 2002-05-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -72901
Name: 2002-05-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -72901
Name: 2002-05-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -72901
Name: 2002-05-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -72901
Name: 2002-05-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -69678
Name: 2002-05-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -69678
Name: 2002-05-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -69678
Name: 2002-05-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -69678
Name: 2002-05-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -69678
Name: 2002-05-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -69678
Name: 2002-05-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -69678
Name: 2002-05-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -71302
Name: 2002-05-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -71302
Name: 2002-05-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -71302
Name: 2002-05-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -71302
Name: 2002-05-31 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -71302
Name: 2002-06-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -71302
Name: 2002-06-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -71302
Name: 2002-06-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -69655
Name: 2002-06-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -69655
Name: 2002-06-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -69655
Name: 2002-06-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -69655
Name: 2002-06-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -69655
Name: 2002-06-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -69655
Name: 2002-06-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -69655
Name: 2002-06-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57533
Name: 2002-06-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57533
Name: 2002-06-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57533
Name: 2002-06-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57533
Name: 2002-06-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57533
Name: 2002-06-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57533
Name: 2002-06-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57533
Name: 2002-06-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -61916
Name: 2002-06-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -61916
Name: 2002-06-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -61916
Name: 2002-06-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -61916
Name: 2002-06-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -61916
Name: 2002-06-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -61916
Name: 2002-06-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -61916
Name: 2002-06-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -53354
Name: 2002-06-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -53354
Name: 2002-06-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -53354
Name: 2002-06-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -53354
Name: 2002-06-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -53354
Name: 2002-06-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -53354
Name: 2002-06-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -53354
Name: 2002-07-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59337
Name: 2002-07-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59337
Name: 2002-07-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59337
Name: 2002-07-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59337
Name: 2002-07-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59337
Name: 2002-07-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59337
Name: 2002-07-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59337
Name: 2002-07-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58651
Name: 2002-07-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58651
Name: 2002-07-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58651
Name: 2002-07-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58651
Name: 2002-07-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58651
Name: 2002-07-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58651
Name: 2002-07-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58651
Name: 2002-07-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56445
Name: 2002-07-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56445
Name: 2002-07-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56445
Name: 2002-07-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56445
Name: 2002-07-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56445
Name: 2002-07-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56445
Name: 2002-07-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56445
Name: 2002-07-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57067
Name: 2002-07-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57067
Name: 2002-07-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57067
Name: 2002-07-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:

Commercials today net:
commercials_net   -38034
Name: 2002-08-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -38034
Name: 2002-08-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45530
Name: 2002-08-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45530
Name: 2002-08-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45530
Name: 2002-08-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45530
Name: 2002-08-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45530
Name: 2002-08-31 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45530
Name: 2002-09-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45530
Name: 2002-09-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -48759
Name: 2002-09-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -48759
Name: 2002-09-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -48759
Name: 2002-09-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -48759
Name: 2002-09-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -48759
Name: 2002-09-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -48759
Name: 2002-09-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -48759
Name: 2002-09-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45579
Name: 2002-09-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45579
Name: 2002-09-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45579
Name: 2002-09-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45579
Name: 2002-09-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45579
Name: 2002-09-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45579
Name: 2002-09-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45579
Name: 2002-09-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -36047
Name: 2002-09-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -36047
Name: 2002-09-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -36047
Name: 2002-09-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -36047
Name: 2002-09-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -36047
Name: 2002-09-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -36047
Name: 2002-09-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -36047
Name: 2002-09-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -37645
Name: 2002-09-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -37645
Name: 2002-09-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -37645
Name: 2002-09-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -37645
Name: 2002-09-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -37645
Name: 2002-09-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -37645
Name: 2002-09-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -37645
Name: 2002-09-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -41482
Name: 2002-10-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -41482
Name: 2002-10-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -41482
Name: 2002-10-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -41482
Name: 2002-10-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -41482
Name: 2002-10-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -41482
Name: 2002-10-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -41482
Name: 2002-10-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -34732
Name: 2002-10-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -34732
Name: 2002-10-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -34732
Name: 2002-10-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -34732
Name: 2002-10-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -34732
Name: 2002-10-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -34732
Name: 2002-10-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -34732
Name: 2002-10-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -44425
Name: 2002-10-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -44425
Name: 2002-10-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -44425
Name: 2002-10-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -44425
Name: 2002-10-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -44425
Name: 2002-10-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -44425
Name: 2002-10-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -44425
Name: 2002-10-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -36095
Name: 2002-10-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -36095
Name: 2002-10-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -36095
Name: 2002-10-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -36095
Name: 2002-10-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -36095
Name: 2002-10-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -36095
Name: 2002-10-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -36095
Name: 2002-10-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43989
Name: 2002-10-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43989
Name: 2002-10-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43989
Name: 2002-10-31 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43989
Name: 2002-11-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43989
Name: 2002-11-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43989
Name: 2002-11-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43989
Name: 2002-11-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -62593
Name: 2002-11-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -62593
Name: 2002-11-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -62593
Name: 2002-11-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -62593
Name: 2002-11-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -62593
Name: 2002-11-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -62593
Name: 2002-11-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -62593
Name: 2002-11-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -62888
Name: 2002-11-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -62888
Name: 2002-11-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -62888
Name: 2002-11-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -62888
Name: 2002-11-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -62888
Name: 2002-11-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -62888
Name: 2002-11-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -62888
Name: 2002-11-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60241
Name: 2002-11-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60241
Name: 2002-11-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60241
Name: 2002-11-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60241
Name: 2002-11-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60241
Name: 2002-11-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60241
Name: 2002-11-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60241
Name: 2002-11-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -55231
Name: 2002-11-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -55231
Name: 2002-11-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -55231
Name: 2002-11-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -55231
Name: 2002-11-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -55231
Name: 2002-11-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -55231
Name: 2002-12-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -55231
Name: 2002-12-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -50444
Name: 2002-12-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -50444
Name: 2002-12-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -50444
Name: 2002-12-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -50444
Name: 2002-12-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -50444
Name: 2002-12-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -50444
Name: 2002-12-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -50444
Name: 2002-12-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57715
Name: 2002-12-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57715
Name: 2002-12-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57715
Name: 2002-12-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57715
Name: 2002-12-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57715
Name: 2002-12-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57715
Name: 2002-12-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57715
Name: 2002-12-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60618
Name: 2002-12-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60618
Name: 2002-12-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60618
Name: 2002-12-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60618
Name: 2002-12-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60618
Name: 2002-12-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -60618
Name: 2002-12-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59542
Name: 2002-12-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59542
Name: 2002-12-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59542
Name: 2002-12-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59542
Name: 2002-12-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59542
Name: 2002-12-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59542
Name: 2002-12-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59542
Name: 2002-12-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59542
Name: 2002-12-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58129
Name: 2002-12-31 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58129
Name: 2003-01-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58129
Name: 2003-01-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58129
Name: 2003-01-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58129
Name: 2003-01-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58129
Name: 2003-01-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58129
Name: 2003-01-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56670
Name: 2003-01-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56670
Name: 2003-01-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56670
Name: 2003-01-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56670
Name: 2003-01-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56670
Name: 2003-01-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56670
Name: 2003-01-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -56670
Name: 2003-01-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58980
Name: 2003-01-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58980
Name: 2003-01-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58980
Name: 2003-01-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58980
Name: 2003-01-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58980
Name: 2003-01-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58980
Name: 2003-01-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58980
Name: 2003-01-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59268
Name: 2003-01-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59268
Name: 2003-01-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59268
Name: 2003-01-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59268
Name: 2003-01-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59268
Name: 2003-01-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59268
Name: 2003-01-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -59268
Name: 2003-01-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -54796
Name: 2003-01-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -54796
Name: 2003-01-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -54796
Name: 2003-01-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -54796
Name: 2003-01-31 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -54796
Name: 2003-02-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -54796
Name: 2003-02-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -54796

Commercials today net:
commercials_net   -47913
Name: 2003-02-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -47913
Name: 2003-02-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -47913
Name: 2003-02-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -47913
Name: 2003-03-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -47913
Name: 2003-03-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -47913
Name: 2003-03-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58719
Name: 2003-03-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58719
Name: 2003-03-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58719
Name: 2003-03-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58719
Name: 2003-03-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58719
Name: 2003-03-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58719
Name: 2003-03-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -58719
Name: 2003-03-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57249
Name: 2003-03-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57249
Name: 2003-03-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57249
Name: 2003-03-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57249
Name: 2003-03-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57249
Name: 2003-03-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57249
Name: 2003-03-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -57249
Name: 2003-03-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -32659
Name: 2003-03-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -32659
Name: 2003-03-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -32659
Name: 2003-03-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -32659
Name: 2003-03-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -32659
Name: 2003-03-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -32659
Name: 2003-03-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -32659
Name: 2003-03-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22336
Name: 2003-03-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22336
Name: 2003-03-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22336
Name: 2003-03-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22336
Name: 2003-03-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22336
Name: 2003-03-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22336
Name: 2003-03-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22336
Name: 2003-03-31 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -28073
Name: 2003-04-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -28073
Name: 2003-04-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -28073
Name: 2003-04-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -28073
Name: 2003-04-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -28073
Name: 2003-04-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -28073
Name: 2003-04-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -28073
Name: 2003-04-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -28791
Name: 2003-04-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -28791
Name: 2003-04-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -28791
Name: 2003-04-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -28791
Name: 2003-04-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -28791
Name: 2003-04-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -28791
Name: 2003-04-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -28791
Name: 2003-04-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -30193
Name: 2003-04-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -30193
Name: 2003-04-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -30193
Name: 2003-04-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -30193
Name: 2003-04-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -30193
Name: 2003-04-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -30193
Name: 2003-04-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -30193
Name: 2003-04-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -42880
Name: 2003-04-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -42880
Name: 2003-04-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -42880
Name: 2003-04-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -42880
Name: 2003-04-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -42880
Name: 2003-04-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -42880
Name: 2003-04-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -42880
Name: 2003-04-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -50641
Name: 2003-04-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -50641
Name: 2003-04-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -50641
Name: 2003-05-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -50641
Name: 2003-05-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -50641
Name: 2003-05-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -50641
Name: 2003-05-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -50641
Name: 2003-05-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -52242
Name: 2003-05-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -52242
Name: 2003-05-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -52242
Name: 2003-05-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -52242
Name: 2003-05-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -52242
Name: 2003-05-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -52242
Name: 2003-05-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -52242
Name: 2003-05-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43720
Name: 2003-05-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43720
Name: 2003-05-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43720
Name: 2003-05-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43720
Name: 2003-05-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43720
Name: 2003-05-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43720
Name: 2003-05-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43720
Name: 2003-05-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -50241
Name: 2003-05-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -50241
Name: 2003-05-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -50241
Name: 2003-05-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -50241
Name: 2003-05-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -50241
Name: 2003-05-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -50241
Name: 2003-05-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -50241
Name: 2003-05-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43296
Name: 2003-05-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43296
Name: 2003-05-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43296
Name: 2003-05-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43296
Name: 2003-05-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43296
Name: 2003-05-31 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43296
Name: 2003-06-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -43296
Name: 2003-06-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -54151
Name: 2003-06-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -54151
Name: 2003-06-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -54151
Name: 2003-06-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -54151
Name: 2003-06-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -54151
Name: 2003-06-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -54151
Name: 2003-06-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -54151
Name: 2003-06-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -48955
Name: 2003-06-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -48955
Name: 2003-06-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -48955
Name: 2003-06-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -48955
Name: 2003-06-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -48955
Name: 2003-06-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -48955
Name: 2003-06-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -48955
Name: 2003-06-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -53677
Name: 2003-06-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -53677
Name: 2003-06-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -53677
Name: 2003-06-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -53677
Name: 2003-06-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -53677
Name: 2003-06-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -53677
Name: 2003-06-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -53677
Name: 2003-06-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -46603
Name: 2003-06-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -46603
Name: 2003-06-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -46603
Name: 2003-06-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -46603
Name: 2003-06-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -46603
Name: 2003-06-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -46603
Name: 2003-06-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -46603
Name: 2003-06-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45951
Name: 2003-07-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45951
Name: 2003-07-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45951
Name: 2003-07-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45951
Name: 2003-07-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45951
Name: 2003-07-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45951
Name: 2003-07-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -45951
Name: 2003-07-07 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39344
Name: 2003-07-08 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39344
Name: 2003-07-09 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39344
Name: 2003-07-10 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39344
Name: 2003-07-11 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39344
Name: 2003-07-12 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39344
Name: 2003-07-13 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -39344
Name: 2003-07-14 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31467
Name: 2003-07-15 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31467
Name: 2003-07-16 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31467
Name: 2003-07-17 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31467
Name: 2003-07-18 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31467
Name: 2003-07-19 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31467
Name: 2003-07-20 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -31467
Name: 2003-07-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -29212
Name: 2003-07-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -29212
Name: 2003-07-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -29212
Name: 2003-07-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -29212
Name: 2003-07-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -29212
Name: 2003-07-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -29212
Name: 2003-07-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -29212
Name: 2003-07-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -34353
Name: 2003-07-29 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -34353
Name: 2003-07-30 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -34353
Name: 2003-07-31 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -34353
Name: 2003-08-01 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -34353
Name: 2003-08-02 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -34353
Name: 2003-08-03 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -34353
Name: 2003-08-04 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -33761
Name: 2003-08-05 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -33761
Name: 2003-08-06 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -33761

No value for this time périod.


Commercials today net:
commercials_net   -22438
Name: 2003-08-21 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22438
Name: 2003-08-22 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22438
Name: 2003-08-23 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22438
Name: 2003-08-24 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -22438
Name: 2003-08-25 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18713
Name: 2003-08-26 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18713
Name: 2003-08-27 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18713
Name: 2003-08-28 00:00:00, dtype: int64


No value for this time périod.


Commercials today net:
commercials_net   -18713
Name: 2003-08-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
76.67736844969255


Commercials today net:
commercials_net   -18713
Name: 2003-08-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
76.67736844969255


Commercials today net:
commercials_net   -18713
Name: 2003-08-31 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
76.67736844969255


Commercials today net:
commercials_net   -18713
Name: 2003-09-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
76.67736844969255


Commercials today net:
commercials_net   -15944
Name: 2003-09-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
80.44430538172716


Commercials today net:
commercials_net   -15944
Name: 2003-09-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
80.44430538172716


Commercials today net:
commercials_net   -15944
Name: 2003-09-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
80.44430538172716


Commercials today net:
commercials_net   -15944
Name: 2003-09-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
80.44430538172716


Commercials today net:
commercials_net   -15944
Name: 2003-09-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
80.44430538172716


Commercials today net:
commercials_net   -15944
Name: 2003-09-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
80.44430538172716


Commercials today net:
commercials_net   -15944
Name: 2003-09-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
80.44430538172716


Commercials today net:
commercials_net   -16611
Name: 2003-09-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
79.5369211514393


Commercials today net:
commercials_net   -16611
Name: 2003-09-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
79.5369211514393


Commercials today net:
commercials_net   -16611
Name: 2003-09-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
79.5369211514393


Commercials today net:
commercials_net   -16611
Name: 2003-09-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
79.5369211514393


Commercials today net:
commercials_net   -16611
Name: 2003-09-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
79.5369211514393


Commercials today net:
commercials_net   -16611
Name: 2003-09-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
79.5369211514393


Commercials today net:
commercials_net   -16611
Name: 2003-09-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
79.5369211514393


Commercials today net:
commercials_net   -22460
Name: 2003-09-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
71.57996408554172


Commercials today net:
commercials_net   -22460
Name: 2003-09-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
71.57996408554172


Commercials today net:
commercials_net   -22460
Name: 2003-09-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
71.57996408554172


Commercials today net:
commercials_net   -22460
Name: 2003-09-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
71.57996408554172


Commercials today net:
commercials_net   -22460
Name: 2003-09-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
71.57996408554172


Commercials today net:
commercials_net   -22460
Name: 2003-09-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
71.57996408554172


Commercials today net:
commercials_net   -22460
Name: 2003-09-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
71.57996408554172


Commercials today net:
commercials_net   -32246
Name: 2003-09-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
58.26712738749524


Commercials today net:
commercials_net   -32246
Name: 2003-09-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
58.26712738749524


Commercials today net:
commercials_net   -32246
Name: 2003-09-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
58.26712738749524


Commercials today net:
commercials_net   -32246
Name: 2003-09-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
58.26712738749524


Commercials today net:
commercials_net   -32246
Name: 2003-09-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
58.26712738749524


Commercials today net:
commercials_net   -32246
Name: 2003-09-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
58.26712738749524


Commercials today net:
commercials_net   -32246
Name: 2003-09-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
58.26712738749524


Commercials today net:
commercials_net   -39847
Name: 2003-09-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
47.92675627142624


Commercials today net:
commercials_net   -39847
Name: 2003-10-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
47.92675627142624


Commercials today net:
commercials_net   -39847
Name: 2003-10-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
47.92675627142624


Commercials today net:
commercials_net   -39847
Name: 2003-10-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
47.92675627142624


Commercials today net:
commercials_net   -39847
Name: 2003-10-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
47.92675627142624


Commercials today net:
commercials_net   -39847
Name: 2003-10-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
47.92675627142624


Commercials today net:
commercials_net   -39847
Name: 2003-10-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
47.92675627142624


Commercials today net:
commercials_net   -45281
Name: 2003-10-07 00:00:00, dtype: int64

Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
40.53436360668227


Commercials today net:
commercials_net   -45281
Name: 2003-10-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
40.53436360668227


Commercials today net:
commercials_net   -45281
Name: 2003-10-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
40.53436360668227


Commercials today net:
commercials_net   -45281
Name: 2003-10-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
40.53436360668227


Commercials today net:
commercials_net   -45281
Name: 2003-10-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
40.53436360668227


Commercials today net:
commercials_net   -45281
Name: 2003-10-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
40.53436360668227


Commercials today net:
commercials_net   -45281
Name: 2003-10-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
40.53436360668227


Commercials today net:
commercials_net   -54005
Name: 2003-10-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
28.66626761713011


Commercials today net:
commercials_net   -54005
Name: 2003-10-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
28.66626761713011


Commercials today net:
commercials_net   -54005
Name: 2003-10-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
28.66626761713011


Commercials today net:
commercials_net   -54005
Name: 2003-10-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
28.66626761713011


Commercials today net:
commercials_net   -54005
Name: 2003-10-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
28.66626761713011


Commercials today net:
commercials_net   -54005
Name: 2003-10-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
28.66626761713011


Commercials today net:
commercials_net   -54005
Name: 2003-10-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
28.66626761713011


Commercials today net:
commercials_net   -50340
Name: 2003-10-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
33.65211949719759


Commercials today net:
commercials_net   -50340
Name: 2003-10-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
33.65211949719759


Commercials today net:
commercials_net   -50340
Name: 2003-10-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
33.65211949719759


Commercials today net:
commercials_net   -50340
Name: 2003-10-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
33.65211949719759


Commercials today net:
commercials_net   -50340
Name: 2003-10-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
33.65211949719759


Commercials today net:
commercials_net   -50340
Name: 2003-10-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
33.65211949719759


Commercials today net:
commercials_net   -50340
Name: 2003-10-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
33.65211949719759


Commercials today net:
commercials_net   -52498
Name: 2003-10-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
30.716384611198784


Commercials today net:
commercials_net   -52498
Name: 2003-10-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
30.716384611198784


Commercials today net:
commercials_net   -52498
Name: 2003-10-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
30.716384611198784


Commercials today net:
commercials_net   -52498
Name: 2003-10-31 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
30.716384611198784


Commercials today net:
commercials_net   -52498
Name: 2003-11-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
30.716384611198784


Commercials today net:
commercials_net   -52498
Name: 2003-11-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
30.716384611198784


Commercials today net:
commercials_net   -52498
Name: 2003-11-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
30.716384611198784


Commercials today net:
commercials_net   -41009
Name: 2003-11-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
46.34597594819611


Commercials today net:
commercials_net   -41009
Name: 2003-11-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
46.34597594819611


Commercials today net:
commercials_net   -41009
Name: 2003-11-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
46.34597594819611


Commercials today net:
commercials_net   -41009
Name: 2003-11-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
46.34597594819611


Commercials today net:
commercials_net   -41009
Name: 2003-11-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
46.34597594819611


Commercials today net:
commercials_net   -41009
Name: 2003-11-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
46.34597594819611


Commercials today net:
commercials_net   -41009
Name: 2003-11-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
46.34597594819611


Commercials today net:
commercials_net   -40153
Name: 2003-11-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
47.510475050334655


Commercials today net:
commercials_net   -40153
Name: 2003-11-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
47.510475050334655


Commercials today net:
commercials_net   -40153
Name: 2003-11-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
47.510475050334655


Commercials today net:
commercials_net   -40153
Name: 2003-11-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
47.510475050334655


Commercials today net:
commercials_net   -40153
Name: 2003-11-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
47.510475050334655


Commercials today net:
commercials_net   -40153
Name: 2003-11-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
47.510475050334655


Commercials today net:
commercials_net   -40153
Name: 2003-11-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
47.510475050334655


Commercials today net:
commercials_net   -55924
Name: 2003-11-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64

Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
26.05566741034989


Commercials today net:
commercials_net   -55924
Name: 2003-11-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
26.05566741034989


Commercials today net:
commercials_net   -55924
Name: 2003-11-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
26.05566741034989


Commercials today net:
commercials_net   -55924
Name: 2003-11-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
26.05566741034989


Commercials today net:
commercials_net   -55924
Name: 2003-11-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
26.05566741034989


Commercials today net:
commercials_net   -55924
Name: 2003-11-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
26.05566741034989


Commercials today net:
commercials_net   -55924
Name: 2003-11-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
26.05566741034989


Commercials today net:
commercials_net   -56103
Name: 2003-11-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
25.812156499972794


Commercials today net:
commercials_net   -56103
Name: 2003-11-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
25.812156499972794


Commercials today net:
commercials_net   -56103
Name: 2003-11-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
25.812156499972794


Commercials today net:
commercials_net   -56103
Name: 2003-11-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
25.812156499972794


Commercials today net:
commercials_net   -56103
Name: 2003-11-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
25.812156499972794


Commercials today net:
commercials_net   -56103
Name: 2003-11-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
25.812156499972794


Commercials today net:
commercials_net   -56103
Name: 2003-12-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
25.812156499972794


Commercials today net:
commercials_net   -55222
Name: 2003-12-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
27.010665505795288


Commercials today net:
commercials_net   -55222
Name: 2003-12-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
27.010665505795288


Commercials today net:
commercials_net   -55222
Name: 2003-12-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
27.010665505795288


Commercials today net:
commercials_net   -55222
Name: 2003-12-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
27.010665505795288


Commercials today net:
commercials_net   -55222
Name: 2003-12-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
27.010665505795288


Commercials today net:
commercials_net   -55222
Name: 2003-12-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
27.010665505795288


Commercials today net:
commercials_net   -55222
Name: 2003-12-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
27.010665505795288


Commercials today net:
commercials_net   -46268
Name: 2003-12-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
39.19165260923981


Commercials today net:
commercials_net   -46268
Name: 2003-12-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
39.19165260923981


Commercials today net:
commercials_net   -46268
Name: 2003-12-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
39.19165260923981


Commercials today net:
commercials_net   -46268
Name: 2003-12-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
39.19165260923981


Commercials today net:
commercials_net   -46268
Name: 2003-12-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
39.19165260923981


Commercials today net:
commercials_net   -46268
Name: 2003-12-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
39.19165260923981


Commercials today net:
commercials_net   -46268
Name: 2003-12-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
39.19165260923981


Commercials today net:
commercials_net   -56104
Name: 2003-12-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
25.810796103825435


Commercials today net:
commercials_net   -56104
Name: 2003-12-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
25.810796103825435


Commercials today net:
commercials_net   -56104
Name: 2003-12-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
25.810796103825435


Commercials today net:
commercials_net   -56104
Name: 2003-12-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
25.810796103825435


Commercials today net:
commercials_net   -56104
Name: 2003-12-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
25.810796103825435


Commercials today net:
commercials_net   -56104
Name: 2003-12-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
25.810796103825435


Commercials today net:
commercials_net   -54299
Name: 2003-12-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
28.26631114980682


Commercials today net:
commercials_net   -54299
Name: 2003-12-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
28.26631114980682


Commercials today net:
commercials_net   -54299
Name: 2003-12-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
28.26631114980682


Commercials today net:
commercials_net   -54299
Name: 2003-12-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
28.26631114980682


Commercials today net:
commercials_net   -54299
Name: 2003-12-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
28.26631114980682


Commercials today net:
commercials_net   -54299
Name: 2003-12-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64

Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
28.26631114980682


Commercials today net:
commercials_net   -54299
Name: 2003-12-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
28.26631114980682


Commercials today net:
commercials_net   -54299
Name: 2003-12-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
28.26631114980682


Commercials today net:
commercials_net   -52275
Name: 2003-12-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
31.019752952059637


Commercials today net:
commercials_net   -52275
Name: 2003-12-31 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
31.019752952059637


Commercials today net:
commercials_net   -52275
Name: 2004-01-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
31.019752952059637


Commercials today net:
commercials_net   -52275
Name: 2004-01-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
31.019752952059637


Commercials today net:
commercials_net   -52275
Name: 2004-01-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
31.019752952059637


Commercials today net:
commercials_net   -52275
Name: 2004-01-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
31.019752952059637


Commercials today net:
commercials_net   -52275
Name: 2004-01-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
31.019752952059637


Commercials today net:
commercials_net   -48822
Name: 2004-01-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
35.717200848887195


Commercials today net:
commercials_net   -48822
Name: 2004-01-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
35.717200848887195


Commercials today net:
commercials_net   -48822
Name: 2004-01-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
35.717200848887195


Commercials today net:
commercials_net   -48822
Name: 2004-01-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
35.717200848887195


Commercials today net:
commercials_net   -48822
Name: 2004-01-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
35.717200848887195


Commercials today net:
commercials_net   -48822
Name: 2004-01-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
35.717200848887195


Commercials today net:
commercials_net   -48822
Name: 2004-01-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
35.717200848887195


Commercials today net:
commercials_net   -50505
Name: 2004-01-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
33.4276541328835


Commercials today net:
commercials_net   -50505
Name: 2004-01-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
33.4276541328835


Commercials today net:
commercials_net   -50505
Name: 2004-01-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
33.4276541328835


Commercials today net:
commercials_net   -50505
Name: 2004-01-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
33.4276541328835


Commercials today net:
commercials_net   -50505
Name: 2004-01-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
33.4276541328835


Commercials today net:
commercials_net   -50505
Name: 2004-01-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
33.4276541328835


Commercials today net:
commercials_net   -50505
Name: 2004-01-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
33.4276541328835


Commercials today net:
commercials_net   -44349
Name: 2004-01-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
41.80225281602002


Commercials today net:
commercials_net   -44349
Name: 2004-01-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
41.80225281602002


Commercials today net:
commercials_net   -44349
Name: 2004-01-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
41.80225281602002


Commercials today net:
commercials_net   -44349
Name: 2004-01-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
41.80225281602002


Commercials today net:
commercials_net   -44349
Name: 2004-01-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
41.80225281602002


Commercials today net:
commercials_net   -44349
Name: 2004-01-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
41.80225281602002


Commercials today net:
commercials_net   -44349
Name: 2004-01-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
41.80225281602002


Commercials today net:
commercials_net   -49884
Name: 2004-01-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
34.27246014039288


Commercials today net:
commercials_net   -49884
Name: 2004-01-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
34.27246014039288


Commercials today net:
commercials_net   -49884
Name: 2004-01-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
34.27246014039288


Commercials today net:
commercials_net   -49884
Name: 2004-01-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
34.27246014039288


Commercials today net:
commercials_net   -49884
Name: 2004-01-31 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
34.27246014039288


Commercials today net:
commercials_net   -49884
Name: 2004-02-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
34.27246014039288


Commercials today net:
commercials_net   -49884
Name: 2004-02-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
34.27246014039288


Commercials today net:
commercials_net   -36721
Name: 2004-02-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
52.1793546280677


Commercials today net:
commercials_net   -36721
Name: 2004-02-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
52.1793546280677


Commercials today net:
commercials_net   -36721
Name: 2004-02-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
52.1793546280677


Commercials today net:
commercials_net   -36721
Name: 2004-02-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
52.1793546280677


Commercials today net:
commercials_net   -36721
Name: 2004-02-07 00:00:00, dtype: int64

Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
52.1793546280677


Commercials today net:
commercials_net   -36721
Name: 2004-02-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
52.1793546280677


Commercials today net:
commercials_net   -36721
Name: 2004-02-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
52.1793546280677


Commercials today net:
commercials_net   -45368
Name: 2004-02-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
40.416009141862105


Commercials today net:
commercials_net   -45368
Name: 2004-02-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
40.416009141862105


Commercials today net:
commercials_net   -45368
Name: 2004-02-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
40.416009141862105


Commercials today net:
commercials_net   -45368
Name: 2004-02-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
40.416009141862105


Commercials today net:
commercials_net   -45368
Name: 2004-02-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
40.416009141862105


Commercials today net:
commercials_net   -45368
Name: 2004-02-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
40.416009141862105


Commercials today net:
commercials_net   -45368
Name: 2004-02-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
40.416009141862105


Commercials today net:
commercials_net   -48060
Name: 2004-02-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
36.75382271317408


Commercials today net:
commercials_net   -48060
Name: 2004-02-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
36.75382271317408


Commercials today net:
commercials_net   -48060
Name: 2004-02-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
36.75382271317408


Commercials today net:
commercials_net   -48060
Name: 2004-02-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
36.75382271317408


Commercials today net:
commercials_net   -48060
Name: 2004-02-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
36.75382271317408


Commercials today net:
commercials_net   -48060
Name: 2004-02-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
36.75382271317408


Commercials today net:
commercials_net   -48060
Name: 2004-02-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
36.75382271317408


Commercials today net:
commercials_net   -39744
Name: 2004-02-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
48.06687707460412


Commercials today net:
commercials_net   -39744
Name: 2004-02-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
48.06687707460412


Commercials today net:
commercials_net   -39744
Name: 2004-02-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
48.06687707460412


Commercials today net:
commercials_net   -39744
Name: 2004-02-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
48.06687707460412


Commercials today net:
commercials_net   -39744
Name: 2004-02-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
48.06687707460412


Commercials today net:
commercials_net   -39744
Name: 2004-02-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
48.06687707460412


Commercials today net:
commercials_net   -39744
Name: 2004-03-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
48.06687707460412


Commercials today net:
commercials_net   -32458
Name: 2004-03-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
57.97872340425532


Commercials today net:
commercials_net   -32458
Name: 2004-03-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
57.97872340425532


Commercials today net:
commercials_net   -32458
Name: 2004-03-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
57.97872340425532


Commercials today net:
commercials_net   -32458
Name: 2004-03-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
57.97872340425532


Commercials today net:
commercials_net   -32458
Name: 2004-03-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
57.97872340425532


Commercials today net:
commercials_net   -32458
Name: 2004-03-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
57.97872340425532


Commercials today net:
commercials_net   -32458
Name: 2004-03-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
57.97872340425532


Commercials today net:
commercials_net   -26254
Name: 2004-03-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
66.41862110246504


Commercials today net:
commercials_net   -26254
Name: 2004-03-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
66.41862110246504


Commercials today net:
commercials_net   -26254
Name: 2004-03-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
66.41862110246504


Commercials today net:
commercials_net   -26254
Name: 2004-03-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
66.41862110246504


Commercials today net:
commercials_net   -26254
Name: 2004-03-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
66.41862110246504


Commercials today net:
commercials_net   -26254
Name: 2004-03-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
66.41862110246504


Commercials today net:
commercials_net   -26254
Name: 2004-03-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
66.41862110246504


Commercials today net:
commercials_net   -19926
Name: 2004-03-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
75.02720792294716


Commercials today net:
commercials_net   -19926
Name: 2004-03-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
75.02720792294716


Commercials today net:
commercials_net   -19926
Name: 2004-03-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
75.02720792294716


Commercials today net:
commercials_net   -19926
Name: 2004-03-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
75.02720792294716


Commercials today net:
commercials_net   -19926
Name: 2004-03-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
75.02720792294716


Commercials today net:
commercials_net   -19926
Name: 2004-03-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
75.02720792294716


Commercials today net:
commercials_net   -19926
Name: 2004-03-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
75.02720792294716


Commercials today net:
commercials_net   -22293
Name: 2004-03-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
71.80715024215051


Commercials today net:
commercials_net   -22293
Name: 2004-03-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
71.80715024215051


Commercials today net:
commercials_net   -22293
Name: 2004-03-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64

Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
71.80715024215051


Commercials today net:
commercials_net   -22293
Name: 2004-03-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
71.80715024215051


Commercials today net:
commercials_net   -22293
Name: 2004-03-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
71.80715024215051


Commercials today net:
commercials_net   -22293
Name: 2004-03-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
71.80715024215051


Commercials today net:
commercials_net   -22293
Name: 2004-03-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
71.80715024215051


Commercials today net:
commercials_net   -13263
Name: 2004-03-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
84.09152745279425


Commercials today net:
commercials_net   -13263
Name: 2004-03-31 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
84.09152745279425


Commercials today net:
commercials_net   -13263
Name: 2004-04-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
84.09152745279425


Commercials today net:
commercials_net   -13263
Name: 2004-04-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
84.09152745279425


Commercials today net:
commercials_net   -13263
Name: 2004-04-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
84.09152745279425


Commercials today net:
commercials_net   -13263
Name: 2004-04-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
84.09152745279425


Commercials today net:
commercials_net   -13263
Name: 2004-04-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
84.09152745279425


Commercials today net:
commercials_net   -11809
Name: 2004-04-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
86.06954345105294


Commercials today net:
commercials_net   -11809
Name: 2004-04-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
86.06954345105294


Commercials today net:
commercials_net   -11809
Name: 2004-04-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
86.06954345105294


Commercials today net:
commercials_net   -11809
Name: 2004-04-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
86.06954345105294


Commercials today net:
commercials_net   -11809
Name: 2004-04-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
86.06954345105294


Commercials today net:
commercials_net   -11809
Name: 2004-04-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
86.06954345105294


Commercials today net:
commercials_net   -13315
Name: 2004-04-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
84.02078685313164


Commercials today net:
commercials_net   -13315
Name: 2004-04-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
84.02078685313164


Commercials today net:
commercials_net   -13315
Name: 2004-04-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
84.02078685313164


Commercials today net:
commercials_net   -13315
Name: 2004-04-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
84.02078685313164


Commercials today net:
commercials_net   -13315
Name: 2004-04-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
84.02078685313164


Commercials today net:
commercials_net   -13315
Name: 2004-04-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
84.02078685313164


Commercials today net:
commercials_net   -13315
Name: 2004-04-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
84.02078685313164


Commercials today net:
commercials_net   -13315
Name: 2004-04-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
84.02078685313164


Commercials today net:
commercials_net   -14332
Name: 2004-04-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
82.63726397126844


Commercials today net:
commercials_net   -14332
Name: 2004-04-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
82.63726397126844


Commercials today net:
commercials_net   -14332
Name: 2004-04-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
82.63726397126844


Commercials today net:
commercials_net   -14332
Name: 2004-04-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
82.63726397126844


Commercials today net:
commercials_net   -14332
Name: 2004-04-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
82.63726397126844


Commercials today net:
commercials_net   -14332
Name: 2004-04-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
82.63726397126844


Commercials today net:
commercials_net   -14332
Name: 2004-04-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
82.63726397126844


Commercials today net:
commercials_net   -9493
Name: 2004-04-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
89.22022092833433


Commercials today net:
commercials_net   -9493
Name: 2004-04-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
89.22022092833433


Commercials today net:
commercials_net   -9493
Name: 2004-04-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
89.22022092833433


Commercials today net:
commercials_net   -9493
Name: 2004-04-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
89.22022092833433


Commercials today net:
commercials_net   -9493
Name: 2004-05-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
89.22022092833433


Commercials today net:
commercials_net   -9493
Name: 2004-05-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
89.22022092833433


Commercials today net:
commercials_net   -9493
Name: 2004-05-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
89.22022092833433


Commercials today net:
commercials_net   -9741
Name: 2004-05-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
88.88284268378952


Commercials today net:
commercials_net   -9741
Name: 2004-05-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
88.88284268378952


Commercials today net:
commercials_net   -9741
Name: 2004-05-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
88.88284268378952


Commercials today net:
commercials_net   -9741
Name: 2004-05-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
88.88284268378952


Commercials today net:
commercials_net   -9741
Name: 2004-05-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
88.88284268378952


Commercials today net:
commercials_net   -9741
Name: 2004-05-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
88.88284268378952


Commercials today net:
commercials_net   -9741
Name: 2004-05-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
88.88284268378952


Commercials today net:
commercials_net   -18920
Name: 2004-05-11 00:00:00, dtype: int64

Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
76.39576644718942


Commercials today net:
commercials_net   -18920
Name: 2004-05-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
76.39576644718942


Commercials today net:
commercials_net   -18920
Name: 2004-05-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
76.39576644718942


Commercials today net:
commercials_net   -18920
Name: 2004-05-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
76.39576644718942


Commercials today net:
commercials_net   -18920
Name: 2004-05-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
76.39576644718942


Commercials today net:
commercials_net   -18920
Name: 2004-05-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
76.39576644718942


Commercials today net:
commercials_net   -18920
Name: 2004-05-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
76.39576644718942


Commercials today net:
commercials_net   -18892
Name: 2004-05-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
76.43385753931545


Commercials today net:
commercials_net   -18892
Name: 2004-05-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
76.43385753931545


Commercials today net:
commercials_net   -18892
Name: 2004-05-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
76.43385753931545


Commercials today net:
commercials_net   -18892
Name: 2004-05-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
76.43385753931545


Commercials today net:
commercials_net   -18892
Name: 2004-05-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
76.43385753931545


Commercials today net:
commercials_net   -18892
Name: 2004-05-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
76.43385753931545


Commercials today net:
commercials_net   -18892
Name: 2004-05-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
76.43385753931545


Commercials today net:
commercials_net   -23815
Name: 2004-05-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
69.73662730587147


Commercials today net:
commercials_net   -23815
Name: 2004-05-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
69.73662730587147


Commercials today net:
commercials_net   -23815
Name: 2004-05-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
69.73662730587147


Commercials today net:
commercials_net   -23815
Name: 2004-05-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
69.73662730587147


Commercials today net:
commercials_net   -23815
Name: 2004-05-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
69.73662730587147


Commercials today net:
commercials_net   -23815
Name: 2004-05-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
69.73662730587147


Commercials today net:
commercials_net   -23815
Name: 2004-05-31 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
69.73662730587147


Commercials today net:
commercials_net   -40846
Name: 2004-06-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
46.56772052021549


Commercials today net:
commercials_net   -40846
Name: 2004-06-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
46.56772052021549


Commercials today net:
commercials_net   -40846
Name: 2004-06-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
46.56772052021549


Commercials today net:
commercials_net   -40846
Name: 2004-06-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
46.56772052021549


Commercials today net:
commercials_net   -40846
Name: 2004-06-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
46.56772052021549


Commercials today net:
commercials_net   -40846
Name: 2004-06-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
46.56772052021549


Commercials today net:
commercials_net   -40846
Name: 2004-06-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
46.56772052021549


Commercials today net:
commercials_net   -43889
Name: 2004-06-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
42.428035043804755


Commercials today net:
commercials_net   -43889
Name: 2004-06-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
42.428035043804755


Commercials today net:
commercials_net   -43889
Name: 2004-06-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
42.428035043804755


Commercials today net:
commercials_net   -43889
Name: 2004-06-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
42.428035043804755


Commercials today net:
commercials_net   -43889
Name: 2004-06-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
42.428035043804755


Commercials today net:
commercials_net   -43889
Name: 2004-06-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
42.428035043804755


Commercials today net:
commercials_net   -43889
Name: 2004-06-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
42.428035043804755


Commercials today net:
commercials_net   -31850
Name: 2004-06-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
58.805844261849046


Commercials today net:
commercials_net   -31850
Name: 2004-06-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
58.805844261849046


Commercials today net:
commercials_net   -31850
Name: 2004-06-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -1569
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
58.805844261849046


Commercials today net:
commercials_net   -31850
Name: 2004-06-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
65.91089290070748


Commercials today net:
commercials_net   -31850
Name: 2004-06-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
65.91089290070748


Commercials today net:
commercials_net   -31850
Name: 2004-06-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
65.91089290070748


Commercials today net:
commercials_net   -31850
Name: 2004-06-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
65.91089290070748


Commercials today net:
commercials_net   -26757
Name: 2004-06-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
73.67650646499146


Commercials today net:
commercials_net   -26757
Name: 2004-06-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
73.67650646499146


Commercials today net:
commercials_net   -26757
Name: 2004-06-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
73.67650646499146


Commercials today net:
commercials_net   -26757
Name: 2004-06-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
73.67650646499146


Commercials today net:
commercials_net   -26757
Name: 2004-06-26 00:00:00, dtype: int64

Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
73.67650646499146


Commercials today net:
commercials_net   -26757
Name: 2004-06-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
73.67650646499146


Commercials today net:
commercials_net   -26757
Name: 2004-06-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
73.67650646499146


Commercials today net:
commercials_net   -27532
Name: 2004-06-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
72.49481580873383


Commercials today net:
commercials_net   -27532
Name: 2004-06-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
72.49481580873383


Commercials today net:
commercials_net   -27532
Name: 2004-07-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
72.49481580873383


Commercials today net:
commercials_net   -27532
Name: 2004-07-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
72.49481580873383


Commercials today net:
commercials_net   -27532
Name: 2004-07-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
72.49481580873383


Commercials today net:
commercials_net   -27532
Name: 2004-07-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
72.49481580873383


Commercials today net:
commercials_net   -27532
Name: 2004-07-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
72.49481580873383


Commercials today net:
commercials_net   -38226
Name: 2004-07-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
56.18900951451573


Commercials today net:
commercials_net   -38226
Name: 2004-07-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
56.18900951451573


Commercials today net:
commercials_net   -38226
Name: 2004-07-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
56.18900951451573


Commercials today net:
commercials_net   -38226
Name: 2004-07-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
56.18900951451573


Commercials today net:
commercials_net   -38226
Name: 2004-07-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
56.18900951451573


Commercials today net:
commercials_net   -38226
Name: 2004-07-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
56.18900951451573


Commercials today net:
commercials_net   -38226
Name: 2004-07-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
56.18900951451573


Commercials today net:
commercials_net   -50400
Name: 2004-07-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
37.62655525737985


Commercials today net:
commercials_net   -50400
Name: 2004-07-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
37.62655525737985


Commercials today net:
commercials_net   -50400
Name: 2004-07-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
37.62655525737985


Commercials today net:
commercials_net   -50400
Name: 2004-07-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
37.62655525737985


Commercials today net:
commercials_net   -50400
Name: 2004-07-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
37.62655525737985


Commercials today net:
commercials_net   -50400
Name: 2004-07-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
37.62655525737985


Commercials today net:
commercials_net   -50400
Name: 2004-07-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
37.62655525737985


Commercials today net:
commercials_net   -55950
Name: 2004-07-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
29.164125396438155


Commercials today net:
commercials_net   -55950
Name: 2004-07-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
29.164125396438155


Commercials today net:
commercials_net   -55950
Name: 2004-07-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
29.164125396438155


Commercials today net:
commercials_net   -55950
Name: 2004-07-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
29.164125396438155


Commercials today net:
commercials_net   -55950
Name: 2004-07-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
29.164125396438155


Commercials today net:
commercials_net   -55950
Name: 2004-07-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
29.164125396438155


Commercials today net:
commercials_net   -55950
Name: 2004-07-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
29.164125396438155


Commercials today net:
commercials_net   -33784
Name: 2004-07-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
62.9620029275433


Commercials today net:
commercials_net   -33784
Name: 2004-07-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
62.9620029275433


Commercials today net:
commercials_net   -33784
Name: 2004-07-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
62.9620029275433


Commercials today net:
commercials_net   -33784
Name: 2004-07-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
62.9620029275433


Commercials today net:
commercials_net   -33784
Name: 2004-07-31 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
62.9620029275433


Commercials today net:
commercials_net   -33784
Name: 2004-08-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
62.9620029275433


Commercials today net:
commercials_net   -33784
Name: 2004-08-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
62.9620029275433


Commercials today net:
commercials_net   -27819
Name: 2004-08-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
72.05720907538424


Commercials today net:
commercials_net   -27819
Name: 2004-08-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
72.05720907538424


Commercials today net:
commercials_net   -27819
Name: 2004-08-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
72.05720907538424


Commercials today net:
commercials_net   -27819
Name: 2004-08-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
72.05720907538424


Commercials today net:
commercials_net   -27819
Name: 2004-08-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
72.05720907538424


Commercials today net:
commercials_net   -27819
Name: 2004-08-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
72.05720907538424


Commercials today net:
commercials_net   -27819
Name: 2004-08-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
72.05720907538424


Commercials today net:
commercials_net   -32130
Name: 2004-08-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
65.48395950231763


Commercials today net:
commercials_net   -32130
Name: 2004-08-11 00:00:00, dtype: int64

Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
65.48395950231763


Commercials today net:
commercials_net   -32130
Name: 2004-08-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
65.48395950231763


Commercials today net:
commercials_net   -32130
Name: 2004-08-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
65.48395950231763


Commercials today net:
commercials_net   -32130
Name: 2004-08-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
65.48395950231763


Commercials today net:
commercials_net   -32130
Name: 2004-08-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
65.48395950231763


Commercials today net:
commercials_net   -32130
Name: 2004-08-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
65.48395950231763


Commercials today net:
commercials_net   -49329
Name: 2004-08-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
39.259575506221026


Commercials today net:
commercials_net   -49329
Name: 2004-08-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
39.259575506221026


Commercials today net:
commercials_net   -49329
Name: 2004-08-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
39.259575506221026


Commercials today net:
commercials_net   -49329
Name: 2004-08-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
39.259575506221026


Commercials today net:
commercials_net   -49329
Name: 2004-08-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
39.259575506221026


Commercials today net:
commercials_net   -49329
Name: 2004-08-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
39.259575506221026


Commercials today net:
commercials_net   -49329
Name: 2004-08-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
39.259575506221026


Commercials today net:
commercials_net   -55057
Name: 2004-08-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
30.525737984874358


Commercials today net:
commercials_net   -55057
Name: 2004-08-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
30.525737984874358


Commercials today net:
commercials_net   -55057
Name: 2004-08-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
30.525737984874358


Commercials today net:
commercials_net   -55057
Name: 2004-08-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
30.525737984874358


Commercials today net:
commercials_net   -55057
Name: 2004-08-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
30.525737984874358


Commercials today net:
commercials_net   -55057
Name: 2004-08-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
30.525737984874358


Commercials today net:
commercials_net   -55057
Name: 2004-08-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
30.525737984874358


Commercials today net:
commercials_net   -48798
Name: 2004-08-31 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
40.06922420102464


Commercials today net:
commercials_net   -48798
Name: 2004-09-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
40.06922420102464


Commercials today net:
commercials_net   -48798
Name: 2004-09-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
40.06922420102464


Commercials today net:
commercials_net   -48798
Name: 2004-09-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
40.06922420102464


Commercials today net:
commercials_net   -48798
Name: 2004-09-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
40.06922420102464


Commercials today net:
commercials_net   -48798
Name: 2004-09-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
40.06922420102464


Commercials today net:
commercials_net   -48798
Name: 2004-09-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
40.06922420102464


Commercials today net:
commercials_net   -44507
Name: 2004-09-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
46.61197853134911


Commercials today net:
commercials_net   -44507
Name: 2004-09-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
46.61197853134911


Commercials today net:
commercials_net   -44507
Name: 2004-09-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
46.61197853134911


Commercials today net:
commercials_net   -44507
Name: 2004-09-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
46.61197853134911


Commercials today net:
commercials_net   -44507
Name: 2004-09-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
46.61197853134911


Commercials today net:
commercials_net   -44507
Name: 2004-09-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
46.61197853134911


Commercials today net:
commercials_net   -44507
Name: 2004-09-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
46.61197853134911


Commercials today net:
commercials_net   -40466
Name: 2004-09-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
52.773542327396925


Commercials today net:
commercials_net   -40466
Name: 2004-09-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
52.773542327396925


Commercials today net:
commercials_net   -40466
Name: 2004-09-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
52.773542327396925


Commercials today net:
commercials_net   -40466
Name: 2004-09-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
52.773542327396925


Commercials today net:
commercials_net   -40466
Name: 2004-09-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
52.773542327396925


Commercials today net:
commercials_net   -40466
Name: 2004-09-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
52.773542327396925


Commercials today net:
commercials_net   -40466
Name: 2004-09-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
52.773542327396925


Commercials today net:
commercials_net   -39241
Name: 2004-09-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
54.64137594535252


Commercials today net:
commercials_net   -39241
Name: 2004-09-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
54.64137594535252


Commercials today net:
commercials_net   -39241
Name: 2004-09-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64

Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
54.64137594535252


Commercials today net:
commercials_net   -39241
Name: 2004-09-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
54.64137594535252


Commercials today net:
commercials_net   -39241
Name: 2004-09-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
54.64137594535252


Commercials today net:
commercials_net   -39241
Name: 2004-09-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
54.64137594535252


Commercials today net:
commercials_net   -39241
Name: 2004-09-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
54.64137594535252


Commercials today net:
commercials_net   -47204
Name: 2004-09-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
42.49969504757258


Commercials today net:
commercials_net   -47204
Name: 2004-09-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
42.49969504757258


Commercials today net:
commercials_net   -47204
Name: 2004-09-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
42.49969504757258


Commercials today net:
commercials_net   -47204
Name: 2004-10-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
42.49969504757258


Commercials today net:
commercials_net   -47204
Name: 2004-10-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
42.49969504757258


Commercials today net:
commercials_net   -47204
Name: 2004-10-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
42.49969504757258


Commercials today net:
commercials_net   -47204
Name: 2004-10-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
42.49969504757258


Commercials today net:
commercials_net   -65992
Name: 2004-10-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
13.852464015613563


Commercials today net:
commercials_net   -65992
Name: 2004-10-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
13.852464015613563


Commercials today net:
commercials_net   -65992
Name: 2004-10-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
13.852464015613563


Commercials today net:
commercials_net   -65992
Name: 2004-10-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
13.852464015613563


Commercials today net:
commercials_net   -65992
Name: 2004-10-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
13.852464015613563


Commercials today net:
commercials_net   -65992
Name: 2004-10-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
13.852464015613563


Commercials today net:
commercials_net   -65992
Name: 2004-10-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
13.852464015613563


Commercials today net:
commercials_net   -62697
Name: 2004-10-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
18.87655525737985


Commercials today net:
commercials_net   -62697
Name: 2004-10-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
18.87655525737985


Commercials today net:
commercials_net   -62697
Name: 2004-10-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
18.87655525737985


Commercials today net:
commercials_net   -62697
Name: 2004-10-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
18.87655525737985


Commercials today net:
commercials_net   -62697
Name: 2004-10-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
18.87655525737985


Commercials today net:
commercials_net   -62697
Name: 2004-10-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
18.87655525737985


Commercials today net:
commercials_net   -62697
Name: 2004-10-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
18.87655525737985


Commercials today net:
commercials_net   -56904
Name: 2004-10-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
27.709502317638446


Commercials today net:
commercials_net   -56904
Name: 2004-10-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
27.709502317638446


Commercials today net:
commercials_net   -56904
Name: 2004-10-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
27.709502317638446


Commercials today net:
commercials_net   -56904
Name: 2004-10-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
27.709502317638446


Commercials today net:
commercials_net   -56904
Name: 2004-10-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
27.709502317638446


Commercials today net:
commercials_net   -56904
Name: 2004-10-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
27.709502317638446


Commercials today net:
commercials_net   -56904
Name: 2004-10-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
27.709502317638446


Commercials today net:
commercials_net   -69957
Name: 2004-10-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
7.806782141985851


Commercials today net:
commercials_net   -69957
Name: 2004-10-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
7.806782141985851


Commercials today net:
commercials_net   -69957
Name: 2004-10-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
7.806782141985851


Commercials today net:
commercials_net   -69957
Name: 2004-10-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
7.806782141985851


Commercials today net:
commercials_net   -69957
Name: 2004-10-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
7.806782141985851


Commercials today net:
commercials_net   -69957
Name: 2004-10-31 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
7.806782141985851


Commercials today net:
commercials_net   -69957
Name: 2004-11-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -75077
dtype: int64


COT INDEX:
7.806782141985851


Commercials today net:
commercials_net   -82061
Name: 2004-11-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82061
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -82061
Name: 2004-11-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82061
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -82061
Name: 2004-11-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82061
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -82061
Name: 2004-11-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82061
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -82061
Name: 2004-11-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82061
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -82061
Name: 2004-11-07 00:00:00, dtype: int64

Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82061
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -82061
Name: 2004-11-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82061
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -82309
Name: 2004-11-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -82309
Name: 2004-11-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -82309
Name: 2004-11-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -82309
Name: 2004-11-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -82309
Name: 2004-11-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -82309
Name: 2004-11-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -82309
Name: 2004-11-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -75292
Name: 2004-11-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
9.636618325642717


Commercials today net:
commercials_net   -75292
Name: 2004-11-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
9.636618325642717


Commercials today net:
commercials_net   -75292
Name: 2004-11-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
9.636618325642717


Commercials today net:
commercials_net   -75292
Name: 2004-11-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
9.636618325642717


Commercials today net:
commercials_net   -75292
Name: 2004-11-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
9.636618325642717


Commercials today net:
commercials_net   -75292
Name: 2004-11-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
9.636618325642717


Commercials today net:
commercials_net   -75292
Name: 2004-11-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
9.636618325642717


Commercials today net:
commercials_net   -66821
Name: 2004-11-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
21.27005053834322


Commercials today net:
commercials_net   -66821
Name: 2004-11-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
21.27005053834322


Commercials today net:
commercials_net   -66821
Name: 2004-11-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
21.27005053834322


Commercials today net:
commercials_net   -66821
Name: 2004-11-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
21.27005053834322


Commercials today net:
commercials_net   -66821
Name: 2004-11-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
21.27005053834322


Commercials today net:
commercials_net   -66821
Name: 2004-11-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
21.27005053834322


Commercials today net:
commercials_net   -66821
Name: 2004-11-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
21.27005053834322


Commercials today net:
commercials_net   -58005
Name: 2004-11-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
33.37727971874314


Commercials today net:
commercials_net   -58005
Name: 2004-12-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
33.37727971874314


Commercials today net:
commercials_net   -58005
Name: 2004-12-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
33.37727971874314


Commercials today net:
commercials_net   -58005
Name: 2004-12-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
33.37727971874314


Commercials today net:
commercials_net   -58005
Name: 2004-12-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
33.37727971874314


Commercials today net:
commercials_net   -58005
Name: 2004-12-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
33.37727971874314


Commercials today net:
commercials_net   -58005
Name: 2004-12-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
33.37727971874314


Commercials today net:
commercials_net   -52553
Name: 2004-12-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
40.86464513293782


Commercials today net:
commercials_net   -52553
Name: 2004-12-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
40.86464513293782


Commercials today net:
commercials_net   -52553
Name: 2004-12-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
40.86464513293782


Commercials today net:
commercials_net   -52553
Name: 2004-12-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
40.86464513293782


Commercials today net:
commercials_net   -52553
Name: 2004-12-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
40.86464513293782


Commercials today net:
commercials_net   -52553
Name: 2004-12-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
40.86464513293782


Commercials today net:
commercials_net   -52553
Name: 2004-12-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net   -9493
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
40.86464513293782


Commercials today net:
commercials_net    4783
Name: 2004-12-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    4783
Name: 2004-12-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    4783
Name: 2004-12-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    4783
Name: 2004-12-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    4783
Name: 2004-12-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    4783
Name: 2004-12-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    4783
Name: 2004-12-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    1962
Name: 2004-12-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.76089652321683


Commercials today net:
commercials_net    1962
Name: 2004-12-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.76089652321683


Commercials today net:
commercials_net    1962
Name: 2004-12-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.76089652321683


Commercials today net:
commercials_net    1962
Name: 2004-12-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.76089652321683


Commercials today net:
commercials_net    1962
Name: 2004-12-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.76089652321683


Commercials today net:
commercials_net    1962
Name: 2004-12-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.76089652321683


Commercials today net:
commercials_net    1962
Name: 2004-12-27 00:00:00, dtype: int64

Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.76089652321683


Commercials today net:
commercials_net   -23374
Name: 2004-12-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
67.66982041978598


Commercials today net:
commercials_net   -23374
Name: 2004-12-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
67.66982041978598


Commercials today net:
commercials_net   -23374
Name: 2004-12-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
67.66982041978598


Commercials today net:
commercials_net   -23374
Name: 2004-12-31 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
67.66982041978598


Commercials today net:
commercials_net   -23374
Name: 2005-01-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
67.66982041978598


Commercials today net:
commercials_net   -23374
Name: 2005-01-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
67.66982041978598


Commercials today net:
commercials_net   -23374
Name: 2005-01-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
67.66982041978598


Commercials today net:
commercials_net   -26163
Name: 2005-01-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
64.46745969779084


Commercials today net:
commercials_net   -26163
Name: 2005-01-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
64.46745969779084


Commercials today net:
commercials_net   -26163
Name: 2005-01-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
64.46745969779084


Commercials today net:
commercials_net   -26163
Name: 2005-01-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
64.46745969779084


Commercials today net:
commercials_net   -26163
Name: 2005-01-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
64.46745969779084


Commercials today net:
commercials_net   -26163
Name: 2005-01-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
64.46745969779084


Commercials today net:
commercials_net   -26163
Name: 2005-01-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
64.46745969779084


Commercials today net:
commercials_net   -29961
Name: 2005-01-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
60.10655398888532


Commercials today net:
commercials_net   -29961
Name: 2005-01-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
60.10655398888532


Commercials today net:
commercials_net   -29961
Name: 2005-01-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
60.10655398888532


Commercials today net:
commercials_net   -29961
Name: 2005-01-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
60.10655398888532


Commercials today net:
commercials_net   -29961
Name: 2005-01-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
60.10655398888532


Commercials today net:
commercials_net   -29961
Name: 2005-01-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
60.10655398888532


Commercials today net:
commercials_net   -29961
Name: 2005-01-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
60.10655398888532


Commercials today net:
commercials_net   -17887
Name: 2005-01-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
73.97005465484774


Commercials today net:
commercials_net   -17887
Name: 2005-01-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
73.97005465484774


Commercials today net:
commercials_net   -17887
Name: 2005-01-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
73.97005465484774


Commercials today net:
commercials_net   -17887
Name: 2005-01-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
73.97005465484774


Commercials today net:
commercials_net   -17887
Name: 2005-01-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
73.97005465484774


Commercials today net:
commercials_net   -17887
Name: 2005-01-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
73.97005465484774


Commercials today net:
commercials_net   -17887
Name: 2005-01-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
73.97005465484774


Commercials today net:
commercials_net   -5398
Name: 2005-01-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
88.31006292196757


Commercials today net:
commercials_net   -5398
Name: 2005-01-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
88.31006292196757


Commercials today net:
commercials_net   -5398
Name: 2005-01-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
88.31006292196757


Commercials today net:
commercials_net   -5398
Name: 2005-01-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
88.31006292196757


Commercials today net:
commercials_net   -5398
Name: 2005-01-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
88.31006292196757


Commercials today net:
commercials_net   -5398
Name: 2005-01-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
88.31006292196757


Commercials today net:
commercials_net   -5398
Name: 2005-01-31 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
88.31006292196757


Commercials today net:
commercials_net   -6425
Name: 2005-02-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
87.13085013548891


Commercials today net:
commercials_net   -6425
Name: 2005-02-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
87.13085013548891


Commercials today net:
commercials_net   -6425
Name: 2005-02-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
87.13085013548891


Commercials today net:
commercials_net   -6425
Name: 2005-02-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
87.13085013548891


Commercials today net:
commercials_net   -6425
Name: 2005-02-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
87.13085013548891


Commercials today net:
commercials_net   -6425
Name: 2005-02-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
87.13085013548891


Commercials today net:
commercials_net   -6425
Name: 2005-02-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
87.13085013548891


Commercials today net:
commercials_net   -7152
Name: 2005-02-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.29610067514812


Commercials today net:
commercials_net   -7152
Name: 2005-02-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.29610067514812


Commercials today net:
commercials_net   -7152
Name: 2005-02-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.29610067514812


Commercials today net:
commercials_net   -7152
Name: 2005-02-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.29610067514812


Commercials today net:
commercials_net   -7152
Name: 2005-02-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.29610067514812


Commercials today net:
commercials_net   -7152
Name: 2005-02-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.29610067514812


Commercials today net:
commercials_net   -7152
Name: 2005-02-14 00:00:00, dtype: int64

Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.29610067514812


Commercials today net:
commercials_net   -3147
Name: 2005-02-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
90.89468607908879


Commercials today net:
commercials_net   -3147
Name: 2005-02-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
90.89468607908879


Commercials today net:
commercials_net   -3147
Name: 2005-02-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
90.89468607908879


Commercials today net:
commercials_net   -3147
Name: 2005-02-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
90.89468607908879


Commercials today net:
commercials_net   -3147
Name: 2005-02-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
90.89468607908879


Commercials today net:
commercials_net   -3147
Name: 2005-02-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
90.89468607908879


Commercials today net:
commercials_net   -3147
Name: 2005-02-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
90.89468607908879


Commercials today net:
commercials_net   -8967
Name: 2005-02-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
84.21209755201396


Commercials today net:
commercials_net   -8967
Name: 2005-02-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
84.21209755201396


Commercials today net:
commercials_net   -8967
Name: 2005-02-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
84.21209755201396


Commercials today net:
commercials_net   -8967
Name: 2005-02-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
84.21209755201396


Commercials today net:
commercials_net   -8967
Name: 2005-02-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
84.21209755201396


Commercials today net:
commercials_net   -8967
Name: 2005-02-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
84.21209755201396


Commercials today net:
commercials_net   -8967
Name: 2005-02-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
84.21209755201396


Commercials today net:
commercials_net   -48220
Name: 2005-03-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
39.141367749046985


Commercials today net:
commercials_net   -48220
Name: 2005-03-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
39.141367749046985


Commercials today net:
commercials_net   -48220
Name: 2005-03-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
39.141367749046985


Commercials today net:
commercials_net   -48220
Name: 2005-03-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
39.141367749046985


Commercials today net:
commercials_net   -48220
Name: 2005-03-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
39.141367749046985


Commercials today net:
commercials_net   -48220
Name: 2005-03-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
39.141367749046985


Commercials today net:
commercials_net   -48220
Name: 2005-03-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
39.141367749046985


Commercials today net:
commercials_net   -38048
Name: 2005-03-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
50.82097092729527


Commercials today net:
commercials_net   -38048
Name: 2005-03-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
50.82097092729527


Commercials today net:
commercials_net   -38048
Name: 2005-03-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
50.82097092729527


Commercials today net:
commercials_net   -38048
Name: 2005-03-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
50.82097092729527


Commercials today net:
commercials_net   -38048
Name: 2005-03-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
50.82097092729527


Commercials today net:
commercials_net   -38048
Name: 2005-03-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
50.82097092729527


Commercials today net:
commercials_net   -38048
Name: 2005-03-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
50.82097092729527


Commercials today net:
commercials_net   -41648
Name: 2005-03-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
46.68741101364075


Commercials today net:
commercials_net   -41648
Name: 2005-03-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
46.68741101364075


Commercials today net:
commercials_net   -41648
Name: 2005-03-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
46.68741101364075


Commercials today net:
commercials_net   -41648
Name: 2005-03-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
46.68741101364075


Commercials today net:
commercials_net   -41648
Name: 2005-03-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
46.68741101364075


Commercials today net:
commercials_net   -41648
Name: 2005-03-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
46.68741101364075


Commercials today net:
commercials_net   -41648
Name: 2005-03-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
46.68741101364075


Commercials today net:
commercials_net   -36310
Name: 2005-03-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
52.816561796720706


Commercials today net:
commercials_net   -36310
Name: 2005-03-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
52.816561796720706


Commercials today net:
commercials_net   -36310
Name: 2005-03-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
52.816561796720706


Commercials today net:
commercials_net   -36310
Name: 2005-03-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
52.816561796720706


Commercials today net:
commercials_net   -36310
Name: 2005-03-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
52.816561796720706


Commercials today net:
commercials_net   -36310
Name: 2005-03-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
52.816561796720706


Commercials today net:
commercials_net   -36310
Name: 2005-03-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
52.816561796720706


Commercials today net:
commercials_net   -24509
Name: 2005-03-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
66.36660083589767


Commercials today net:
commercials_net   -24509
Name: 2005-03-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
66.36660083589767


Commercials today net:
commercials_net   -24509
Name: 2005-03-31 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
66.36660083589767


Commercials today net:
commercials_net   -24509
Name: 2005-04-01 00:00:00, dtype: int64

Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
66.36660083589767


Commercials today net:
commercials_net   -24509
Name: 2005-04-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
66.36660083589767


Commercials today net:
commercials_net   -24509
Name: 2005-04-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
66.36660083589767


Commercials today net:
commercials_net   -24509
Name: 2005-04-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
66.36660083589767


Commercials today net:
commercials_net   -7382
Name: 2005-04-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.03201212510908


Commercials today net:
commercials_net   -7382
Name: 2005-04-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.03201212510908


Commercials today net:
commercials_net   -7382
Name: 2005-04-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.03201212510908


Commercials today net:
commercials_net   -7382
Name: 2005-04-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.03201212510908


Commercials today net:
commercials_net   -7382
Name: 2005-04-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.03201212510908


Commercials today net:
commercials_net   -7382
Name: 2005-04-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.03201212510908


Commercials today net:
commercials_net   -7382
Name: 2005-04-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.03201212510908


Commercials today net:
commercials_net   -10554
Name: 2005-04-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
82.3898865567446


Commercials today net:
commercials_net   -10554
Name: 2005-04-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
82.3898865567446


Commercials today net:
commercials_net   -10554
Name: 2005-04-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
82.3898865567446


Commercials today net:
commercials_net   -10554
Name: 2005-04-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
82.3898865567446


Commercials today net:
commercials_net   -10554
Name: 2005-04-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
82.3898865567446


Commercials today net:
commercials_net   -10554
Name: 2005-04-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
82.3898865567446


Commercials today net:
commercials_net   -10554
Name: 2005-04-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
82.3898865567446


Commercials today net:
commercials_net   -10732
Name: 2005-04-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
82.18550498323611


Commercials today net:
commercials_net   -10732
Name: 2005-04-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
82.18550498323611


Commercials today net:
commercials_net   -10732
Name: 2005-04-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
82.18550498323611


Commercials today net:
commercials_net   -10732
Name: 2005-04-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
82.18550498323611


Commercials today net:
commercials_net   -10732
Name: 2005-04-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
82.18550498323611


Commercials today net:
commercials_net   -10732
Name: 2005-04-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
82.18550498323611


Commercials today net:
commercials_net   -10732
Name: 2005-04-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
82.18550498323611


Commercials today net:
commercials_net   -6177
Name: 2005-04-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
87.41560648509622


Commercials today net:
commercials_net   -6177
Name: 2005-04-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
87.41560648509622


Commercials today net:
commercials_net   -6177
Name: 2005-04-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
87.41560648509622


Commercials today net:
commercials_net   -6177
Name: 2005-04-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
87.41560648509622


Commercials today net:
commercials_net   -6177
Name: 2005-04-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
87.41560648509622


Commercials today net:
commercials_net   -6177
Name: 2005-05-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
87.41560648509622


Commercials today net:
commercials_net   -6177
Name: 2005-05-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
87.41560648509622


Commercials today net:
commercials_net   -7052
Name: 2005-05-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.41092178386074


Commercials today net:
commercials_net   -7052
Name: 2005-05-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.41092178386074


Commercials today net:
commercials_net   -7052
Name: 2005-05-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.41092178386074


Commercials today net:
commercials_net   -7052
Name: 2005-05-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.41092178386074


Commercials today net:
commercials_net   -7052
Name: 2005-05-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.41092178386074


Commercials today net:
commercials_net   -7052
Name: 2005-05-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.41092178386074


Commercials today net:
commercials_net   -7052
Name: 2005-05-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.41092178386074


Commercials today net:
commercials_net    2338
Name: 2005-05-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
97.19262389197631


Commercials today net:
commercials_net    2338
Name: 2005-05-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
97.19262389197631


Commercials today net:
commercials_net    2338
Name: 2005-05-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
97.19262389197631


Commercials today net:
commercials_net    2338
Name: 2005-05-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
97.19262389197631


Commercials today net:
commercials_net    2338
Name: 2005-05-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
97.19262389197631


Commercials today net:
commercials_net    2338
Name: 2005-05-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
97.19262389197631


Commercials today net:
commercials_net    2338
Name: 2005-05-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    4783
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
97.19262389197631


Commercials today net:
commercials_net    18099
Name: 2005-05-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    18099
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    18099
Name: 2005-05-18 00:00:00, dtype: int64

Commercial max past 3 years
commercials_net    18099
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    18099
Name: 2005-05-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    18099
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    18099
Name: 2005-05-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    18099
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    18099
Name: 2005-05-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    18099
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    18099
Name: 2005-05-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    18099
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    18099
Name: 2005-05-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    18099
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    23798
Name: 2005-05-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    23798
Name: 2005-05-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    23798
Name: 2005-05-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    23798
Name: 2005-05-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    23798
Name: 2005-05-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    23798
Name: 2005-05-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    23798
Name: 2005-05-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    19694
Name: 2005-05-31 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.13220616924426


Commercials today net:
commercials_net    19694
Name: 2005-06-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.13220616924426


Commercials today net:
commercials_net    19694
Name: 2005-06-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.13220616924426


Commercials today net:
commercials_net    19694
Name: 2005-06-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.13220616924426


Commercials today net:
commercials_net    19694
Name: 2005-06-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.13220616924426


Commercials today net:
commercials_net    19694
Name: 2005-06-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.13220616924426


Commercials today net:
commercials_net    19694
Name: 2005-06-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.13220616924426


Commercials today net:
commercials_net    19936
Name: 2005-06-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.36027783275372


Commercials today net:
commercials_net    19936
Name: 2005-06-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.36027783275372


Commercials today net:
commercials_net    19936
Name: 2005-06-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.36027783275372


Commercials today net:
commercials_net    19936
Name: 2005-06-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.36027783275372


Commercials today net:
commercials_net    19936
Name: 2005-06-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.36027783275372


Commercials today net:
commercials_net    19936
Name: 2005-06-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.36027783275372


Commercials today net:
commercials_net    19936
Name: 2005-06-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.36027783275372


Commercials today net:
commercials_net    22809
Name: 2005-06-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
99.06792200326086


Commercials today net:
commercials_net    22809
Name: 2005-06-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
99.06792200326086


Commercials today net:
commercials_net    22809
Name: 2005-06-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
99.06792200326086


Commercials today net:
commercials_net    22809
Name: 2005-06-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
99.06792200326086


Commercials today net:
commercials_net    22809
Name: 2005-06-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
99.06792200326086


Commercials today net:
commercials_net    22809
Name: 2005-06-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
99.06792200326086


Commercials today net:
commercials_net    22809
Name: 2005-06-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    23798
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
99.06792200326086


Commercials today net:
commercials_net    24902
Name: 2005-06-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    24902
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    24902
Name: 2005-06-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    24902
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    24902
Name: 2005-06-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    24902
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    24902
Name: 2005-06-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    24902
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    24902
Name: 2005-06-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    24902
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    24902
Name: 2005-06-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    24902
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    24902
Name: 2005-06-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    24902
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    16279
Name: 2005-06-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    24902
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
91.95698202609806


Commercials today net:
commercials_net    16279
Name: 2005-06-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    24902
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
91.95698202609806


Commercials today net:
commercials_net    16279
Name: 2005-06-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    24902
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
91.95698202609806


Commercials today net:
commercials_net    16279
Name: 2005-07-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    24902
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
91.95698202609806


Commercials today net:
commercials_net    16279
Name: 2005-07-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    24902
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
91.95698202609806


Commercials today net:
commercials_net    16279
Name: 2005-07-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    24902
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
91.95698202609806


Commercials today net:
commercials_net    16279
Name: 2005-07-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    24902
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
91.95698202609806


Commercials today net:
commercials_net    27394
Name: 2005-07-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    27394
Name: 2005-07-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    27394
Name: 2005-07-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    27394
Name: 2005-07-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    27394
Name: 2005-07-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    27394
Name: 2005-07-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    27394
Name: 2005-07-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
100.0


Commercials today net:
commercials_net    13802
Name: 2005-07-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
87.61018386005853


Commercials today net:
commercials_net    13802
Name: 2005-07-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
87.61018386005853


Commercials today net:
commercials_net    13802
Name: 2005-07-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
87.61018386005853


Commercials today net:
commercials_net    13802
Name: 2005-07-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
87.61018386005853


Commercials today net:
commercials_net    13802
Name: 2005-07-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
87.61018386005853


Commercials today net:
commercials_net    13802
Name: 2005-07-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
87.61018386005853


Commercials today net:
commercials_net    13802
Name: 2005-07-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
87.61018386005853


Commercials today net:
commercials_net    14686
Name: 2005-07-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
88.41599591624659


Commercials today net:
commercials_net    14686
Name: 2005-07-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
88.41599591624659


Commercials today net:
commercials_net    14686
Name: 2005-07-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
88.41599591624659


Commercials today net:
commercials_net    14686
Name: 2005-07-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
88.41599591624659


Commercials today net:
commercials_net    14686
Name: 2005-07-23 00:00:00, dtype: int64

Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
88.41599591624659


Commercials today net:
commercials_net    14686
Name: 2005-07-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
88.41599591624659


Commercials today net:
commercials_net    14686
Name: 2005-07-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
88.41599591624659


Commercials today net:
commercials_net    7107
Name: 2005-07-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
81.50734255216356


Commercials today net:
commercials_net    7107
Name: 2005-07-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
81.50734255216356


Commercials today net:
commercials_net    7107
Name: 2005-07-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
81.50734255216356


Commercials today net:
commercials_net    7107
Name: 2005-07-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
81.50734255216356


Commercials today net:
commercials_net    7107
Name: 2005-07-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
81.50734255216356


Commercials today net:
commercials_net    7107
Name: 2005-07-31 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
81.50734255216356


Commercials today net:
commercials_net    7107
Name: 2005-08-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
81.50734255216356


Commercials today net:
commercials_net   -1818
Name: 2005-08-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
73.37174006180324


Commercials today net:
commercials_net   -1818
Name: 2005-08-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
73.37174006180324


Commercials today net:
commercials_net   -1818
Name: 2005-08-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
73.37174006180324


Commercials today net:
commercials_net   -1818
Name: 2005-08-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
73.37174006180324


Commercials today net:
commercials_net   -1818
Name: 2005-08-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
73.37174006180324


Commercials today net:
commercials_net   -1818
Name: 2005-08-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
73.37174006180324


Commercials today net:
commercials_net   -1818
Name: 2005-08-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
73.37174006180324


Commercials today net:
commercials_net   -4118
Name: 2005-08-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
71.27517023235464


Commercials today net:
commercials_net   -4118
Name: 2005-08-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
71.27517023235464


Commercials today net:
commercials_net   -4118
Name: 2005-08-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
71.27517023235464


Commercials today net:
commercials_net   -4118
Name: 2005-08-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
71.27517023235464


Commercials today net:
commercials_net   -4118
Name: 2005-08-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
71.27517023235464


Commercials today net:
commercials_net   -4118
Name: 2005-08-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
71.27517023235464


Commercials today net:
commercials_net   -4118
Name: 2005-08-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
71.27517023235464


Commercials today net:
commercials_net   -3966
Name: 2005-08-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
71.41372615151819


Commercials today net:
commercials_net   -3966
Name: 2005-08-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
71.41372615151819


Commercials today net:
commercials_net   -3966
Name: 2005-08-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
71.41372615151819


Commercials today net:
commercials_net   -3966
Name: 2005-08-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
71.41372615151819


Commercials today net:
commercials_net   -3966
Name: 2005-08-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
71.41372615151819


Commercials today net:
commercials_net   -3966
Name: 2005-08-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
71.41372615151819


Commercials today net:
commercials_net   -3966
Name: 2005-08-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
71.41372615151819


Commercials today net:
commercials_net    4786
Name: 2005-08-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
79.39163012862001


Commercials today net:
commercials_net    4786
Name: 2005-08-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
79.39163012862001


Commercials today net:
commercials_net    4786
Name: 2005-08-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
79.39163012862001


Commercials today net:
commercials_net    4786
Name: 2005-08-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
79.39163012862001


Commercials today net:
commercials_net    4786
Name: 2005-08-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
79.39163012862001


Commercials today net:
commercials_net    4786
Name: 2005-08-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
79.39163012862001


Commercials today net:
commercials_net    4786
Name: 2005-08-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
79.39163012862001


Commercials today net:
commercials_net    2661
Name: 2005-08-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
77.45458191662945


Commercials today net:
commercials_net    2661
Name: 2005-08-31 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
77.45458191662945


Commercials today net:
commercials_net    2661
Name: 2005-09-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
77.45458191662945


Commercials today net:
commercials_net    2661
Name: 2005-09-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64

Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
77.45458191662945


Commercials today net:
commercials_net    2661
Name: 2005-09-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
77.45458191662945


Commercials today net:
commercials_net    2661
Name: 2005-09-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
77.45458191662945


Commercials today net:
commercials_net    2661
Name: 2005-09-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
77.45458191662945


Commercials today net:
commercials_net   -29311
Name: 2005-09-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
48.310438183094355


Commercials today net:
commercials_net   -29311
Name: 2005-09-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
48.310438183094355


Commercials today net:
commercials_net   -29311
Name: 2005-09-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
48.310438183094355


Commercials today net:
commercials_net   -29311
Name: 2005-09-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
48.310438183094355


Commercials today net:
commercials_net   -29311
Name: 2005-09-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
48.310438183094355


Commercials today net:
commercials_net   -29311
Name: 2005-09-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
48.310438183094355


Commercials today net:
commercials_net   -29311
Name: 2005-09-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
48.310438183094355


Commercials today net:
commercials_net   -12936
Name: 2005-09-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
63.237103816668636


Commercials today net:
commercials_net   -12936
Name: 2005-09-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
63.237103816668636


Commercials today net:
commercials_net   -12936
Name: 2005-09-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
63.237103816668636


Commercials today net:
commercials_net   -12936
Name: 2005-09-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
63.237103816668636


Commercials today net:
commercials_net   -12936
Name: 2005-09-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
63.237103816668636


Commercials today net:
commercials_net   -12936
Name: 2005-09-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
63.237103816668636


Commercials today net:
commercials_net   -12936
Name: 2005-09-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
63.237103816668636


Commercials today net:
commercials_net    5485
Name: 2005-09-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
80.02880504635243


Commercials today net:
commercials_net    5485
Name: 2005-09-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
80.02880504635243


Commercials today net:
commercials_net    5485
Name: 2005-09-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
80.02880504635243


Commercials today net:
commercials_net    5485
Name: 2005-09-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
80.02880504635243


Commercials today net:
commercials_net    5485
Name: 2005-09-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
80.02880504635243


Commercials today net:
commercials_net    5485
Name: 2005-09-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
80.02880504635243


Commercials today net:
commercials_net    5485
Name: 2005-09-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
80.02880504635243


Commercials today net:
commercials_net    7688
Name: 2005-09-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
82.03695432212427


Commercials today net:
commercials_net    7688
Name: 2005-09-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
82.03695432212427


Commercials today net:
commercials_net    7688
Name: 2005-09-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
82.03695432212427


Commercials today net:
commercials_net    7688
Name: 2005-09-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
82.03695432212427


Commercials today net:
commercials_net    7688
Name: 2005-10-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
82.03695432212427


Commercials today net:
commercials_net    7688
Name: 2005-10-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
82.03695432212427


Commercials today net:
commercials_net    7688
Name: 2005-10-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
82.03695432212427


Commercials today net:
commercials_net    12582
Name: 2005-10-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.498090298351


Commercials today net:
commercials_net    12582
Name: 2005-10-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.498090298351


Commercials today net:
commercials_net    12582
Name: 2005-10-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.498090298351


Commercials today net:
commercials_net    12582
Name: 2005-10-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.498090298351


Commercials today net:
commercials_net    12582
Name: 2005-10-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.498090298351


Commercials today net:
commercials_net    12582
Name: 2005-10-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.498090298351


Commercials today net:
commercials_net    12582
Name: 2005-10-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.498090298351


Commercials today net:
commercials_net    2639
Name: 2005-10-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
77.43452777043473


Commercials today net:
commercials_net    2639
Name: 2005-10-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
77.43452777043473


Commercials today net:
commercials_net    2639
Name: 2005-10-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
77.43452777043473


Commercials today net:
commercials_net    2639
Name: 2005-10-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
77.43452777043473


Commercials today net:
commercials_net    2639
Name: 2005-10-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
77.43452777043473


Commercials today net:
commercials_net    2639
Name: 2005-10-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
77.43452777043473


Commercials today net:
commercials_net    2639
Name: 2005-10-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
77.43452777043473


Commercials today net:
commercials_net    4757
Name: 2005-10-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
79.36519511772696


Commercials today net:
commercials_net    4757
Name: 2005-10-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64

Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
79.36519511772696


Commercials today net:
commercials_net    4757
Name: 2005-10-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
79.36519511772696


Commercials today net:
commercials_net    4757
Name: 2005-10-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
79.36519511772696


Commercials today net:
commercials_net    4757
Name: 2005-10-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
79.36519511772696


Commercials today net:
commercials_net    4757
Name: 2005-10-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
79.36519511772696


Commercials today net:
commercials_net    4757
Name: 2005-10-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
79.36519511772696


Commercials today net:
commercials_net    7371
Name: 2005-10-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
81.74799230650028


Commercials today net:
commercials_net    7371
Name: 2005-10-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
81.74799230650028


Commercials today net:
commercials_net    7371
Name: 2005-10-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
81.74799230650028


Commercials today net:
commercials_net    7371
Name: 2005-10-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
81.74799230650028


Commercials today net:
commercials_net    7371
Name: 2005-10-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
81.74799230650028


Commercials today net:
commercials_net    7371
Name: 2005-10-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
81.74799230650028


Commercials today net:
commercials_net    7371
Name: 2005-10-31 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
81.74799230650028


Commercials today net:
commercials_net   -1621
Name: 2005-11-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
73.551315825456


Commercials today net:
commercials_net   -1621
Name: 2005-11-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
73.551315825456


Commercials today net:
commercials_net   -1621
Name: 2005-11-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
73.551315825456


Commercials today net:
commercials_net   -1621
Name: 2005-11-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
73.551315825456


Commercials today net:
commercials_net   -1621
Name: 2005-11-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
73.551315825456


Commercials today net:
commercials_net   -1621
Name: 2005-11-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
73.551315825456


Commercials today net:
commercials_net   -1621
Name: 2005-11-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
73.551315825456


Commercials today net:
commercials_net    12433
Name: 2005-11-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.36226903548673


Commercials today net:
commercials_net    12433
Name: 2005-11-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.36226903548673


Commercials today net:
commercials_net    12433
Name: 2005-11-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.36226903548673


Commercials today net:
commercials_net    12433
Name: 2005-11-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.36226903548673


Commercials today net:
commercials_net    12433
Name: 2005-11-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.36226903548673


Commercials today net:
commercials_net    12433
Name: 2005-11-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.36226903548673


Commercials today net:
commercials_net    12433
Name: 2005-11-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
86.36226903548673


Commercials today net:
commercials_net    20672
Name: 2005-11-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
93.87254678541152


Commercials today net:
commercials_net    20672
Name: 2005-11-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
93.87254678541152


Commercials today net:
commercials_net    20672
Name: 2005-11-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
93.87254678541152


Commercials today net:
commercials_net    20672
Name: 2005-11-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
93.87254678541152


Commercials today net:
commercials_net    20672
Name: 2005-11-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
93.87254678541152


Commercials today net:
commercials_net    20672
Name: 2005-11-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
93.87254678541152


Commercials today net:
commercials_net    20672
Name: 2005-11-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
93.87254678541152


Commercials today net:
commercials_net    16910
Name: 2005-11-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
90.44328778611342


Commercials today net:
commercials_net    16910
Name: 2005-11-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
90.44328778611342


Commercials today net:
commercials_net    16910
Name: 2005-11-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
90.44328778611342


Commercials today net:
commercials_net    16910
Name: 2005-11-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
90.44328778611342


Commercials today net:
commercials_net    16910
Name: 2005-11-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
90.44328778611342


Commercials today net:
commercials_net    16910
Name: 2005-11-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
90.44328778611342


Commercials today net:
commercials_net    16910
Name: 2005-11-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
90.44328778611342


Commercials today net:
commercials_net    17901
Name: 2005-11-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
91.34663591697584


Commercials today net:
commercials_net    17901
Name: 2005-11-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
91.34663591697584


Commercials today net:
commercials_net    17901
Name: 2005-12-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
91.34663591697584


Commercials today net:
commercials_net    17901
Name: 2005-12-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
91.34663591697584


Commercials today net:
commercials_net    17901
Name: 2005-12-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
91.34663591697584


Commercials today net:
commercials_net    17901
Name: 2005-12-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
91.34663591697584


Commercials today net:
commercials_net    17901
Name: 2005-12-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
91.34663591697584


Commercials today net:
commercials_net    23395
Name: 2005-12-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.35470315305872


Commercials today net:
commercials_net    23395
Name: 2005-12-07 00:00:00, dtype: int64

Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.35470315305872


Commercials today net:
commercials_net    23395
Name: 2005-12-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.35470315305872


Commercials today net:
commercials_net    23395
Name: 2005-12-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.35470315305872


Commercials today net:
commercials_net    23395
Name: 2005-12-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.35470315305872


Commercials today net:
commercials_net    23395
Name: 2005-12-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.35470315305872


Commercials today net:
commercials_net    23395
Name: 2005-12-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
96.35470315305872


Commercials today net:
commercials_net    3321
Name: 2005-12-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
78.05620630247122


Commercials today net:
commercials_net    3321
Name: 2005-12-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
78.05620630247122


Commercials today net:
commercials_net    3321
Name: 2005-12-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
78.05620630247122


Commercials today net:
commercials_net    3321
Name: 2005-12-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
78.05620630247122


Commercials today net:
commercials_net    3321
Name: 2005-12-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
78.05620630247122


Commercials today net:
commercials_net    3321
Name: 2005-12-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
78.05620630247122


Commercials today net:
commercials_net    3321
Name: 2005-12-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
78.05620630247122


Commercials today net:
commercials_net   -7994
Name: 2005-12-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
67.74199429368386


Commercials today net:
commercials_net   -7994
Name: 2005-12-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
67.74199429368386


Commercials today net:
commercials_net   -7994
Name: 2005-12-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
67.74199429368386


Commercials today net:
commercials_net   -7994
Name: 2005-12-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
67.74199429368386


Commercials today net:
commercials_net   -7994
Name: 2005-12-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
67.74199429368386


Commercials today net:
commercials_net   -7994
Name: 2005-12-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
67.74199429368386


Commercials today net:
commercials_net   -7994
Name: 2005-12-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
67.74199429368386


Commercials today net:
commercials_net   -6095
Name: 2005-12-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
69.47303173112859


Commercials today net:
commercials_net   -6095
Name: 2005-12-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
69.47303173112859


Commercials today net:
commercials_net   -6095
Name: 2005-12-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
69.47303173112859


Commercials today net:
commercials_net   -6095
Name: 2005-12-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
69.47303173112859


Commercials today net:
commercials_net   -6095
Name: 2005-12-31 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
69.47303173112859


Commercials today net:
commercials_net   -6095
Name: 2006-01-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
69.47303173112859


Commercials today net:
commercials_net   -6095
Name: 2006-01-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
69.47303173112859


Commercials today net:
commercials_net   -11689
Name: 2006-01-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
64.37380928506968


Commercials today net:
commercials_net   -11689
Name: 2006-01-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
64.37380928506968


Commercials today net:
commercials_net   -11689
Name: 2006-01-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
64.37380928506968


Commercials today net:
commercials_net   -11689
Name: 2006-01-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
64.37380928506968


Commercials today net:
commercials_net   -11689
Name: 2006-01-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
64.37380928506968


Commercials today net:
commercials_net   -11689
Name: 2006-01-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
64.37380928506968


Commercials today net:
commercials_net   -11689
Name: 2006-01-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
64.37380928506968


Commercials today net:
commercials_net   -28204
Name: 2006-01-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
49.319526357528964


Commercials today net:
commercials_net   -28204
Name: 2006-01-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
49.319526357528964


Commercials today net:
commercials_net   -28204
Name: 2006-01-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
49.319526357528964


Commercials today net:
commercials_net   -28204
Name: 2006-01-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
49.319526357528964


Commercials today net:
commercials_net   -28204
Name: 2006-01-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
49.319526357528964


Commercials today net:
commercials_net   -28204
Name: 2006-01-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
49.319526357528964


Commercials today net:
commercials_net   -28204
Name: 2006-01-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
49.319526357528964


Commercials today net:
commercials_net   -33518
Name: 2006-01-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
44.47553849940293


Commercials today net:
commercials_net   -33518
Name: 2006-01-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
44.47553849940293


Commercials today net:
commercials_net   -33518
Name: 2006-01-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
44.47553849940293


Commercials today net:
commercials_net   -33518
Name: 2006-01-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
44.47553849940293


Commercials today net:
commercials_net   -33518
Name: 2006-01-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64

COT INDEX:
44.47553849940293


Commercials today net:
commercials_net   -33518
Name: 2006-01-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
44.47553849940293


Commercials today net:
commercials_net   -33518
Name: 2006-01-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
44.47553849940293


Commercials today net:
commercials_net   -55850
Name: 2006-01-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
24.118757007556766


Commercials today net:
commercials_net   -55850
Name: 2006-01-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
24.118757007556766


Commercials today net:
commercials_net   -55850
Name: 2006-01-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
24.118757007556766


Commercials today net:
commercials_net   -55850
Name: 2006-01-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
24.118757007556766


Commercials today net:
commercials_net   -55850
Name: 2006-01-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
24.118757007556766


Commercials today net:
commercials_net   -55850
Name: 2006-01-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
24.118757007556766


Commercials today net:
commercials_net   -55850
Name: 2006-01-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
24.118757007556766


Commercials today net:
commercials_net   -52990
Name: 2006-01-31 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
26.72579601287112


Commercials today net:
commercials_net   -52990
Name: 2006-02-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
26.72579601287112


Commercials today net:
commercials_net   -52990
Name: 2006-02-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
26.72579601287112


Commercials today net:
commercials_net   -52990
Name: 2006-02-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
26.72579601287112


Commercials today net:
commercials_net   -52990
Name: 2006-02-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
26.72579601287112


Commercials today net:
commercials_net   -52990
Name: 2006-02-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
26.72579601287112


Commercials today net:
commercials_net   -52990
Name: 2006-02-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
26.72579601287112


Commercials today net:
commercials_net   -30673
Name: 2006-02-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
47.068904223220876


Commercials today net:
commercials_net   -30673
Name: 2006-02-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
47.068904223220876


Commercials today net:
commercials_net   -30673
Name: 2006-02-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
47.068904223220876


Commercials today net:
commercials_net   -30673
Name: 2006-02-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
47.068904223220876


Commercials today net:
commercials_net   -30673
Name: 2006-02-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
47.068904223220876


Commercials today net:
commercials_net   -30673
Name: 2006-02-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
47.068904223220876


Commercials today net:
commercials_net   -30673
Name: 2006-02-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
47.068904223220876


Commercials today net:
commercials_net   -19446
Name: 2006-02-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
57.30289964722933


Commercials today net:
commercials_net   -19446
Name: 2006-02-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
57.30289964722933


Commercials today net:
commercials_net   -19446
Name: 2006-02-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
57.30289964722933


Commercials today net:
commercials_net   -19446
Name: 2006-02-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
57.30289964722933


Commercials today net:
commercials_net   -19446
Name: 2006-02-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
57.30289964722933


Commercials today net:
commercials_net   -19446
Name: 2006-02-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
57.30289964722933


Commercials today net:
commercials_net   -19446
Name: 2006-02-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
57.30289964722933


Commercials today net:
commercials_net   -16737
Name: 2006-02-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
59.77229428547989


Commercials today net:
commercials_net   -16737
Name: 2006-02-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
59.77229428547989


Commercials today net:
commercials_net   -16737
Name: 2006-02-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
59.77229428547989


Commercials today net:
commercials_net   -16737
Name: 2006-02-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
59.77229428547989


Commercials today net:
commercials_net   -16737
Name: 2006-02-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
59.77229428547989


Commercials today net:
commercials_net   -16737
Name: 2006-02-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
59.77229428547989


Commercials today net:
commercials_net   -16737
Name: 2006-02-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
59.77229428547989


Commercials today net:
commercials_net   -25649
Name: 2006-02-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
51.64854197241643


Commercials today net:
commercials_net   -25649
Name: 2006-03-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
51.64854197241643


Commercials today net:
commercials_net   -25649
Name: 2006-03-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
51.64854197241643


Commercials today net:
commercials_net   -25649
Name: 2006-03-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
51.64854197241643


Commercials today net:
commercials_net   -25649
Name: 2006-03-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
51.64854197241643


Commercials today net:
commercials_net   -25649
Name: 2006-03-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
51.64854197241643


Commercials today net:
commercials_net   -25649
Name: 2006-03-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64

Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
51.64854197241643


Commercials today net:
commercials_net   -22695
Name: 2006-03-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
54.34126687510825


Commercials today net:
commercials_net   -22695
Name: 2006-03-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
54.34126687510825


Commercials today net:
commercials_net   -22695
Name: 2006-03-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
54.34126687510825


Commercials today net:
commercials_net   -22695
Name: 2006-03-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
54.34126687510825


Commercials today net:
commercials_net   -22695
Name: 2006-03-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
54.34126687510825


Commercials today net:
commercials_net   -22695
Name: 2006-03-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
54.34126687510825


Commercials today net:
commercials_net   -22695
Name: 2006-03-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
54.34126687510825


Commercials today net:
commercials_net   -34042
Name: 2006-03-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
43.997885199128554


Commercials today net:
commercials_net   -34042
Name: 2006-03-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
43.997885199128554


Commercials today net:
commercials_net   -34042
Name: 2006-03-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
43.997885199128554


Commercials today net:
commercials_net   -34042
Name: 2006-03-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
43.997885199128554


Commercials today net:
commercials_net   -34042
Name: 2006-03-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
43.997885199128554


Commercials today net:
commercials_net   -34042
Name: 2006-03-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
43.997885199128554


Commercials today net:
commercials_net   -34042
Name: 2006-03-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
43.997885199128554


Commercials today net:
commercials_net   -54712
Name: 2006-03-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
25.15610329708394


Commercials today net:
commercials_net   -54712
Name: 2006-03-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
25.15610329708394


Commercials today net:
commercials_net   -54712
Name: 2006-03-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
25.15610329708394


Commercials today net:
commercials_net   -54712
Name: 2006-03-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
25.15610329708394


Commercials today net:
commercials_net   -54712
Name: 2006-03-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
25.15610329708394


Commercials today net:
commercials_net   -54712
Name: 2006-03-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
25.15610329708394


Commercials today net:
commercials_net   -54712
Name: 2006-03-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
25.15610329708394


Commercials today net:
commercials_net   -57902
Name: 2006-03-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
22.24825209884871


Commercials today net:
commercials_net   -57902
Name: 2006-03-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
22.24825209884871


Commercials today net:
commercials_net   -57902
Name: 2006-03-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
22.24825209884871


Commercials today net:
commercials_net   -57902
Name: 2006-03-31 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
22.24825209884871


Commercials today net:
commercials_net   -57902
Name: 2006-04-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
22.24825209884871


Commercials today net:
commercials_net   -57902
Name: 2006-04-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
22.24825209884871


Commercials today net:
commercials_net   -57902
Name: 2006-04-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
22.24825209884871


Commercials today net:
commercials_net   -69401
Name: 2006-04-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
11.766314503705459


Commercials today net:
commercials_net   -69401
Name: 2006-04-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
11.766314503705459


Commercials today net:
commercials_net   -69401
Name: 2006-04-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
11.766314503705459


Commercials today net:
commercials_net   -69401
Name: 2006-04-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
11.766314503705459


Commercials today net:
commercials_net   -69401
Name: 2006-04-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
11.766314503705459


Commercials today net:
commercials_net   -69401
Name: 2006-04-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
11.766314503705459


Commercials today net:
commercials_net   -69401
Name: 2006-04-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
11.766314503705459


Commercials today net:
commercials_net   -64058
Name: 2006-04-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
16.63673737272454


Commercials today net:
commercials_net   -64058
Name: 2006-04-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
16.63673737272454


Commercials today net:
commercials_net   -64058
Name: 2006-04-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
16.63673737272454


Commercials today net:
commercials_net   -64058
Name: 2006-04-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
16.63673737272454


Commercials today net:
commercials_net   -64058
Name: 2006-04-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
16.63673737272454


Commercials today net:
commercials_net   -64058
Name: 2006-04-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
16.63673737272454


Commercials today net:
commercials_net   -64058
Name: 2006-04-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
16.63673737272454


Commercials today net:
commercials_net   -79964
Name: 2006-04-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64

Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
2.137589673937814


Commercials today net:
commercials_net   -79964
Name: 2006-04-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
2.137589673937814


Commercials today net:
commercials_net   -79964
Name: 2006-04-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
2.137589673937814


Commercials today net:
commercials_net   -79964
Name: 2006-04-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
2.137589673937814


Commercials today net:
commercials_net   -79964
Name: 2006-04-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
2.137589673937814


Commercials today net:
commercials_net   -79964
Name: 2006-04-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
2.137589673937814


Commercials today net:
commercials_net   -79964
Name: 2006-04-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -82309
dtype: int64


COT INDEX:
2.137589673937814


Commercials today net:
commercials_net   -92283
Name: 2006-04-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -92283
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -92283
Name: 2006-04-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -92283
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -92283
Name: 2006-04-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -92283
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -92283
Name: 2006-04-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -92283
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -92283
Name: 2006-04-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -92283
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -92283
Name: 2006-04-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -92283
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -92283
Name: 2006-05-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -92283
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -98998
Name: 2006-05-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -98998
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -98998
Name: 2006-05-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -98998
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -98998
Name: 2006-05-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -98998
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -98998
Name: 2006-05-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -98998
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -98998
Name: 2006-05-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -98998
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -98998
Name: 2006-05-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -98998
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -98998
Name: 2006-05-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -98998
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -99413
Name: 2006-05-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99413
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -99413
Name: 2006-05-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99413
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -99413
Name: 2006-05-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99413
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -99413
Name: 2006-05-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99413
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -99413
Name: 2006-05-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99413
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -99413
Name: 2006-05-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99413
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -99413
Name: 2006-05-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99413
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -97845
Name: 2006-05-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99413
dtype: int64


COT INDEX:
1.2365247975269504


Commercials today net:
commercials_net   -97845
Name: 2006-05-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99413
dtype: int64


COT INDEX:
1.2365247975269504


Commercials today net:
commercials_net   -97845
Name: 2006-05-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99413
dtype: int64


COT INDEX:
1.2365247975269504


Commercials today net:
commercials_net   -97845
Name: 2006-05-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99413
dtype: int64


COT INDEX:
1.2365247975269504


Commercials today net:
commercials_net   -97845
Name: 2006-05-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99413
dtype: int64


COT INDEX:
1.2365247975269504


Commercials today net:
commercials_net   -97845
Name: 2006-05-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99413
dtype: int64


COT INDEX:
1.2365247975269504


Commercials today net:
commercials_net   -97845
Name: 2006-05-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99413
dtype: int64


COT INDEX:
1.2365247975269504


Commercials today net:
commercials_net   -95985
Name: 2006-05-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99413
dtype: int64


COT INDEX:
2.7033207945933584


Commercials today net:
commercials_net   -95985
Name: 2006-05-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99413
dtype: int64


COT INDEX:
2.7033207945933584


Commercials today net:
commercials_net   -95985
Name: 2006-05-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99413
dtype: int64


COT INDEX:
2.7033207945933584


Commercials today net:
commercials_net   -95985
Name: 2006-05-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99413
dtype: int64


COT INDEX:
2.7033207945933584


Commercials today net:
commercials_net   -95985
Name: 2006-05-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99413
dtype: int64


COT INDEX:
2.7033207945933584


Commercials today net:
commercials_net   -95985
Name: 2006-05-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99413
dtype: int64


COT INDEX:
2.7033207945933584


Commercials today net:
commercials_net   -95985
Name: 2006-05-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99413
dtype: int64


COT INDEX:
2.7033207945933584


Commercials today net:
commercials_net   -99886
Name: 2006-05-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99886
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -99886
Name: 2006-05-31 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99886
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -99886
Name: 2006-06-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99886
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -99886
Name: 2006-06-02 00:00:00, dtype: int64

Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99886
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -99886
Name: 2006-06-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99886
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -99886
Name: 2006-06-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99886
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -99886
Name: 2006-06-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -99886
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -114226
Name: 2006-06-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -114226
Name: 2006-06-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -114226
Name: 2006-06-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -114226
Name: 2006-06-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -114226
Name: 2006-06-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -114226
Name: 2006-06-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -114226
Name: 2006-06-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -88030
Name: 2006-06-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
18.497387374664594


Commercials today net:
commercials_net   -88030
Name: 2006-06-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
18.497387374664594


Commercials today net:
commercials_net   -88030
Name: 2006-06-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
18.497387374664594


Commercials today net:
commercials_net   -88030
Name: 2006-06-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
18.497387374664594


Commercials today net:
commercials_net   -88030
Name: 2006-06-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
18.497387374664594


Commercials today net:
commercials_net   -88030
Name: 2006-06-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
18.497387374664594


Commercials today net:
commercials_net   -88030
Name: 2006-06-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
18.497387374664594


Commercials today net:
commercials_net   -76569
Name: 2006-06-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
26.590170879819237


Commercials today net:
commercials_net   -76569
Name: 2006-06-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
26.590170879819237


Commercials today net:
commercials_net   -76569
Name: 2006-06-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
26.590170879819237


Commercials today net:
commercials_net   -76569
Name: 2006-06-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
26.590170879819237


Commercials today net:
commercials_net   -76569
Name: 2006-06-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
26.590170879819237


Commercials today net:
commercials_net   -76569
Name: 2006-06-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
26.590170879819237


Commercials today net:
commercials_net   -76569
Name: 2006-06-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
26.590170879819237


Commercials today net:
commercials_net   -88446
Name: 2006-06-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
18.20364355317046


Commercials today net:
commercials_net   -88446
Name: 2006-06-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
18.20364355317046


Commercials today net:
commercials_net   -88446
Name: 2006-06-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
18.20364355317046


Commercials today net:
commercials_net   -88446
Name: 2006-06-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
18.20364355317046


Commercials today net:
commercials_net   -88446
Name: 2006-07-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
18.20364355317046


Commercials today net:
commercials_net   -88446
Name: 2006-07-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
18.20364355317046


Commercials today net:
commercials_net   -92663
Name: 2006-07-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
15.225956785764721


Commercials today net:
commercials_net   -92663
Name: 2006-07-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
15.225956785764721


Commercials today net:
commercials_net   -92663
Name: 2006-07-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
15.225956785764721


Commercials today net:
commercials_net   -92663
Name: 2006-07-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
15.225956785764721


Commercials today net:
commercials_net   -92663
Name: 2006-07-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
15.225956785764721


Commercials today net:
commercials_net   -92663
Name: 2006-07-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
15.225956785764721


Commercials today net:
commercials_net   -92663
Name: 2006-07-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
15.225956785764721


Commercials today net:
commercials_net   -92663
Name: 2006-07-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
15.225956785764721


Commercials today net:
commercials_net   -108781
Name: 2006-07-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
3.8447959327778567


Commercials today net:
commercials_net   -108781
Name: 2006-07-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
3.8447959327778567


Commercials today net:
commercials_net   -108781
Name: 2006-07-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
3.8447959327778567


Commercials today net:
commercials_net   -108781
Name: 2006-07-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
3.8447959327778567


Commercials today net:
commercials_net   -108781
Name: 2006-07-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
3.8447959327778567


Commercials today net:
commercials_net   -108781
Name: 2006-07-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
3.8447959327778567


Commercials today net:
commercials_net   -108781
Name: 2006-07-17 00:00:00, dtype: int64

Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
3.8447959327778567


Commercials today net:
commercials_net   -71930
Name: 2006-07-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
29.865838158452195


Commercials today net:
commercials_net   -71930
Name: 2006-07-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
29.865838158452195


Commercials today net:
commercials_net   -71930
Name: 2006-07-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
29.865838158452195


Commercials today net:
commercials_net   -71930
Name: 2006-07-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
29.865838158452195


Commercials today net:
commercials_net   -71930
Name: 2006-07-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
29.865838158452195


Commercials today net:
commercials_net   -71930
Name: 2006-07-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
29.865838158452195


Commercials today net:
commercials_net   -71930
Name: 2006-07-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
29.865838158452195


Commercials today net:
commercials_net   -69815
Name: 2006-07-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
31.359271289365907


Commercials today net:
commercials_net   -69815
Name: 2006-07-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
31.359271289365907


Commercials today net:
commercials_net   -69815
Name: 2006-07-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
31.359271289365907


Commercials today net:
commercials_net   -69815
Name: 2006-07-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
31.359271289365907


Commercials today net:
commercials_net   -69815
Name: 2006-07-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
31.359271289365907


Commercials today net:
commercials_net   -69815
Name: 2006-07-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
31.359271289365907


Commercials today net:
commercials_net   -69815
Name: 2006-07-31 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
31.359271289365907


Commercials today net:
commercials_net   -97863
Name: 2006-08-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
11.554159017087983


Commercials today net:
commercials_net   -97863
Name: 2006-08-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
11.554159017087983


Commercials today net:
commercials_net   -97863
Name: 2006-08-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
11.554159017087983


Commercials today net:
commercials_net   -97863
Name: 2006-08-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
11.554159017087983


Commercials today net:
commercials_net   -97863
Name: 2006-08-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
11.554159017087983


Commercials today net:
commercials_net   -97863
Name: 2006-08-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
11.554159017087983


Commercials today net:
commercials_net   -97863
Name: 2006-08-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -114226
dtype: int64


COT INDEX:
11.554159017087983


Commercials today net:
commercials_net   -121815
Name: 2006-08-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -121815
Name: 2006-08-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -121815
Name: 2006-08-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -121815
Name: 2006-08-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -121815
Name: 2006-08-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -121815
Name: 2006-08-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -121815
Name: 2006-08-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -117729
Name: 2006-08-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
2.738440710680991


Commercials today net:
commercials_net   -117729
Name: 2006-08-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
2.738440710680991


Commercials today net:
commercials_net   -117729
Name: 2006-08-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
2.738440710680991


Commercials today net:
commercials_net   -117729
Name: 2006-08-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
2.738440710680991


Commercials today net:
commercials_net   -117729
Name: 2006-08-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
2.738440710680991


Commercials today net:
commercials_net   -117729
Name: 2006-08-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
2.738440710680991


Commercials today net:
commercials_net   -117729
Name: 2006-08-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
2.738440710680991


Commercials today net:
commercials_net   -111856
Name: 2006-08-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64

Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
6.674530356747916


Commercials today net:
commercials_net   -111856
Name: 2006-08-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
6.674530356747916


Commercials today net:
commercials_net   -111856
Name: 2006-08-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
6.674530356747916


Commercials today net:
commercials_net   -111856
Name: 2006-08-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
6.674530356747916


Commercials today net:
commercials_net   -111856
Name: 2006-08-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
6.674530356747916


Commercials today net:
commercials_net   -111856
Name: 2006-08-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
6.674530356747916


Commercials today net:
commercials_net   -111856
Name: 2006-08-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
6.674530356747916


Commercials today net:
commercials_net   -104466
Name: 2006-08-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
11.627314706217454


Commercials today net:
commercials_net   -104466
Name: 2006-08-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
11.627314706217454


Commercials today net:
commercials_net   -104466
Name: 2006-08-31 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
11.627314706217454


Commercials today net:
commercials_net   -104466
Name: 2006-09-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
11.627314706217454


Commercials today net:
commercials_net   -104466
Name: 2006-09-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
11.627314706217454


Commercials today net:
commercials_net   -104466
Name: 2006-09-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
11.627314706217454


Commercials today net:
commercials_net   -104466
Name: 2006-09-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
11.627314706217454


Commercials today net:
commercials_net   -104103
Name: 2006-09-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
11.870597618106146


Commercials today net:
commercials_net   -104103
Name: 2006-09-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
11.870597618106146


Commercials today net:
commercials_net   -104103
Name: 2006-09-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
11.870597618106146


Commercials today net:
commercials_net   -104103
Name: 2006-09-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
11.870597618106146


Commercials today net:
commercials_net   -104103
Name: 2006-09-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
11.870597618106146


Commercials today net:
commercials_net   -104103
Name: 2006-09-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
11.870597618106146


Commercials today net:
commercials_net   -104103
Name: 2006-09-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
11.870597618106146


Commercials today net:
commercials_net   -84604
Name: 2006-09-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
24.93884417159823


Commercials today net:
commercials_net   -84604
Name: 2006-09-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
24.93884417159823


Commercials today net:
commercials_net   -84604
Name: 2006-09-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
24.93884417159823


Commercials today net:
commercials_net   -84604
Name: 2006-09-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
24.93884417159823


Commercials today net:
commercials_net   -84604
Name: 2006-09-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
24.93884417159823


Commercials today net:
commercials_net   -84604
Name: 2006-09-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
24.93884417159823


Commercials today net:
commercials_net   -84604
Name: 2006-09-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
24.93884417159823


Commercials today net:
commercials_net   -64512
Name: 2006-09-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
38.40451983459443


Commercials today net:
commercials_net   -64512
Name: 2006-09-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
38.40451983459443


Commercials today net:
commercials_net   -64512
Name: 2006-09-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
38.40451983459443


Commercials today net:
commercials_net   -64512
Name: 2006-09-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
38.40451983459443


Commercials today net:
commercials_net   -64512
Name: 2006-09-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64

Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
38.40451983459443


Commercials today net:
commercials_net   -64512
Name: 2006-09-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
38.40451983459443


Commercials today net:
commercials_net   -64512
Name: 2006-09-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
38.40451983459443


Commercials today net:
commercials_net   -69584
Name: 2006-09-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
35.005261076744695


Commercials today net:
commercials_net   -69584
Name: 2006-09-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
35.005261076744695


Commercials today net:
commercials_net   -69584
Name: 2006-09-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
35.005261076744695


Commercials today net:
commercials_net   -69584
Name: 2006-09-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
35.005261076744695


Commercials today net:
commercials_net   -69584
Name: 2006-09-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
35.005261076744695


Commercials today net:
commercials_net   -69584
Name: 2006-10-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
35.005261076744695


Commercials today net:
commercials_net   -69584
Name: 2006-10-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
35.005261076744695


Commercials today net:
commercials_net   -71868
Name: 2006-10-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
33.474522314337605


Commercials today net:
commercials_net   -71868
Name: 2006-10-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
33.474522314337605


Commercials today net:
commercials_net   -71868
Name: 2006-10-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
33.474522314337605


Commercials today net:
commercials_net   -71868
Name: 2006-10-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
33.474522314337605


Commercials today net:
commercials_net   -71868
Name: 2006-10-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
33.474522314337605


Commercials today net:
commercials_net   -71868
Name: 2006-10-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
33.474522314337605


Commercials today net:
commercials_net   -71868
Name: 2006-10-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
33.474522314337605


Commercials today net:
commercials_net   -49824
Name: 2006-10-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
48.24843005448733


Commercials today net:
commercials_net   -49824
Name: 2006-10-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
48.24843005448733


Commercials today net:
commercials_net   -49824
Name: 2006-10-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
48.24843005448733


Commercials today net:
commercials_net   -49824
Name: 2006-10-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
48.24843005448733


Commercials today net:
commercials_net   -49824
Name: 2006-10-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
48.24843005448733


Commercials today net:
commercials_net   -49824
Name: 2006-10-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
48.24843005448733


Commercials today net:
commercials_net   -49824
Name: 2006-10-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
48.24843005448733


Commercials today net:
commercials_net   -34922
Name: 2006-10-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
58.2357632582485


Commercials today net:
commercials_net   -34922
Name: 2006-10-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
58.2357632582485


Commercials today net:
commercials_net   -34922
Name: 2006-10-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
58.2357632582485


Commercials today net:
commercials_net   -34922
Name: 2006-10-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
58.2357632582485


Commercials today net:
commercials_net   -34922
Name: 2006-10-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
58.2357632582485


Commercials today net:
commercials_net   -34922
Name: 2006-10-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
58.2357632582485


Commercials today net:
commercials_net   -34922
Name: 2006-10-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
58.2357632582485


Commercials today net:
commercials_net   -31893
Name: 2006-10-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
60.26580166075773


Commercials today net:
commercials_net   -31893
Name: 2006-10-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
60.26580166075773


Commercials today net:
commercials_net   -31893
Name: 2006-10-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
60.26580166075773


Commercials today net:
commercials_net   -31893
Name: 2006-10-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
60.26580166075773


Commercials today net:
commercials_net   -31893
Name: 2006-10-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
60.26580166075773


Commercials today net:
commercials_net   -31893
Name: 2006-10-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
60.26580166075773


Commercials today net:
commercials_net   -31893
Name: 2006-10-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
60.26580166075773


Commercials today net:
commercials_net   -78279
Name: 2006-10-31 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
29.177864606022425


Commercials today net:
commercials_net   -78279
Name: 2006-11-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
29.177864606022425


Commercials today net:
commercials_net   -78279
Name: 2006-11-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
29.177864606022425


Commercials today net:
commercials_net   -78279
Name: 2006-11-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
29.177864606022425


Commercials today net:
commercials_net   -78279
Name: 2006-11-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
29.177864606022425


Commercials today net:
commercials_net   -78279
Name: 2006-11-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
29.177864606022425


Commercials today net:
commercials_net   -78279
Name: 2006-11-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
29.177864606022425


Commercials today net:
commercials_net   -94122
Name: 2006-11-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
18.559872393756407


Commercials today net:
commercials_net   -94122
Name: 2006-11-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
18.559872393756407


Commercials today net:
commercials_net   -94122
Name: 2006-11-09 00:00:00, dtype: int64

Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
18.559872393756407


Commercials today net:
commercials_net   -94122
Name: 2006-11-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
18.559872393756407


Commercials today net:
commercials_net   -94122
Name: 2006-11-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
18.559872393756407


Commercials today net:
commercials_net   -94122
Name: 2006-11-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
18.559872393756407


Commercials today net:
commercials_net   -94122
Name: 2006-11-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
18.559872393756407


Commercials today net:
commercials_net   -84266
Name: 2006-11-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
25.165372062006984


Commercials today net:
commercials_net   -84266
Name: 2006-11-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
25.165372062006984


Commercials today net:
commercials_net   -84266
Name: 2006-11-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
25.165372062006984


Commercials today net:
commercials_net   -84266
Name: 2006-11-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
25.165372062006984


Commercials today net:
commercials_net   -84266
Name: 2006-11-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
25.165372062006984


Commercials today net:
commercials_net   -84266
Name: 2006-11-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
25.165372062006984


Commercials today net:
commercials_net   -84266
Name: 2006-11-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
25.165372062006984


Commercials today net:
commercials_net   -90115
Name: 2006-11-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
21.245367236560796


Commercials today net:
commercials_net   -90115
Name: 2006-11-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
21.245367236560796


Commercials today net:
commercials_net   -90115
Name: 2006-11-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
21.245367236560796


Commercials today net:
commercials_net   -90115
Name: 2006-11-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
21.245367236560796


Commercials today net:
commercials_net   -90115
Name: 2006-11-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
21.245367236560796


Commercials today net:
commercials_net   -90115
Name: 2006-11-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
21.245367236560796


Commercials today net:
commercials_net   -90115
Name: 2006-11-27 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
21.245367236560796


Commercials today net:
commercials_net   -108836
Name: 2006-11-28 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
8.698536951524371


Commercials today net:
commercials_net   -108836
Name: 2006-11-29 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
8.698536951524371


Commercials today net:
commercials_net   -108836
Name: 2006-11-30 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
8.698536951524371


Commercials today net:
commercials_net   -108836
Name: 2006-12-01 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
8.698536951524371


Commercials today net:
commercials_net   -108836
Name: 2006-12-02 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
8.698536951524371


Commercials today net:
commercials_net   -108836
Name: 2006-12-03 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
8.698536951524371


Commercials today net:
commercials_net   -108836
Name: 2006-12-04 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -121815
dtype: int64


COT INDEX:
8.698536951524371


Commercials today net:
commercials_net   -128314
Name: 2006-12-05 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -128314
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -128314
Name: 2006-12-06 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -128314
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -128314
Name: 2006-12-07 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -128314
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -128314
Name: 2006-12-08 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -128314
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -128314
Name: 2006-12-09 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -128314
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -128314
Name: 2006-12-10 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -128314
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -128314
Name: 2006-12-11 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -128314
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -129244
Name: 2006-12-12 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -129244
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -129244
Name: 2006-12-13 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -129244
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -129244
Name: 2006-12-14 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -129244
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -129244
Name: 2006-12-15 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -129244
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -129244
Name: 2006-12-16 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -129244
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -129244
Name: 2006-12-17 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -129244
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -129244
Name: 2006-12-18 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -129244
dtype: int64


COT INDEX:
0.0


Commercials today net:
commercials_net   -124999
Name: 2006-12-19 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -129244
dtype: int64


COT INDEX:
2.710070353298689


Commercials today net:
commercials_net   -124999
Name: 2006-12-20 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -129244
dtype: int64


COT INDEX:
2.710070353298689


Commercials today net:
commercials_net   -124999
Name: 2006-12-21 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -129244
dtype: int64


COT INDEX:
2.710070353298689


Commercials today net:
commercials_net   -124999
Name: 2006-12-22 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -129244
dtype: int64


COT INDEX:
2.710070353298689


Commercials today net:
commercials_net   -124999
Name: 2006-12-23 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -129244
dtype: int64


COT INDEX:
2.710070353298689


Commercials today net:
commercials_net   -124999
Name: 2006-12-24 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -129244
dtype: int64


COT INDEX:
2.710070353298689


Commercials today net:
commercials_net   -124999
Name: 2006-12-25 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -129244
dtype: int64


COT INDEX:
2.710070353298689


Commercials today net:
commercials_net   -115965
Name: 2006-12-26 00:00:00, dtype: int64


Commercial max past 3 years
commercials_net    27394
dtype: int64
Commercial min past 3 years
commercials_net   -129244
dtype: int64


COT INDEX:
8.477508650519031

In [210]:
test = pd.read_csv(r'C:\Users\timmo\Google Drive\1.Trading\4.Data\COT\cot_index_eurusud.csv')
test

            date  cot_index
0     2003-08-29  76.677368
1     2003-08-30  76.677368
2     2003-08-31  76.677368
3     2003-09-01  76.677368
4     2003-09-02  80.444305
...          ...        ...
1211  2006-12-22   2.710070
1212  2006-12-23   2.710070
1213  2006-12-24   2.710070
1214  2006-12-25   2.710070
1215  2006-12-26   8.477509

[1216 rows x 2 columns]